(function(){var l,aa;function ba(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}var ha="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){if(a==Array.prototype||a==Object.prototype)return a;a[b]=c.value;return a}; 
function ia(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var c=a[b];if(c&&c.Math==Math)return c}throw Error("Cannot find global object");}var ja=ia(this),ka="function"===typeof Symbol&&"symbol"===typeof Symbol("x"),r={},la={};function u(a,b,c){if(!c||null!=a){c=la[b];if(null==c)return a[b];c=a[c];return void 0!==c?c:a[b]}} 
function v(a,b,c){if(b)a:{var d=a.split(".");a=1===d.length;var e=d[0],f;!a&&e in r?f=r:f=ja;for(e=0;e<d.length-1;e++){var g=d[e];if(!(g in f))break a;f=f[g]}d=d[d.length-1];c=ka&&"es6"===c?f[d]:null;b=b(c);null!=b&&(a?ha(r,d,{configurable:!0,writable:!0,value:b}):b!==c&&(void 0===la[d]&&(a=1E9*Math.random()>>>0,la[d]=ka?ja.Symbol(d):"$jscp$"+a+"$"+d),ha(f,la[d],{configurable:!0,writable:!0,value:b})))}} 
v("Symbol",function(a){function b(f){if(this instanceof b)throw new TypeError("Symbol is not a constructor");return new c(d+(f||"")+"_"+e++,f)}function c(f,g){this.g=f;ha(this,"description",{configurable:!0,writable:!0,value:g})}if(a)return a;c.prototype.toString=function(){return this.g};var d="jscomp_symbol_"+(1E9*Math.random()>>>0)+"_",e=0;return b},"es6"); 
v("Symbol.iterator",function(a){if(a)return a;a=(0,r.Symbol)("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),c=0;c<b.length;c++){var d=ja[b[c]];"function"===typeof d&&"function"!=typeof d.prototype[a]&&ha(d.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(ba(this))}})}return a},"es6"); 
function ma(a){a={next:a};a[u(r.Symbol,"iterator")]=function(){return this};return a}function na(a){var b="undefined"!=typeof r.Symbol&&u(r.Symbol,"iterator")&&a[u(r.Symbol,"iterator")];if(b)return b.call(a);if("number"==typeof a.length)return{next:ba(a)};throw Error(String(a)+" is not an iterable or ArrayLike");}function oa(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c} 
var pa=ka&&"function"==typeof u(Object,"assign")?u(Object,"assign"):function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(d)for(var e in d)Object.prototype.hasOwnProperty.call(d,e)&&(a[e]=d[e])}return a};v("Object.assign",function(a){return a||pa},"es6"); 
function qa(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}v("String.prototype.endsWith",function(a){return a?a:function(b,c){var d=qa(this,b,"endsWith");void 0===c&&(c=d.length);c=Math.max(0,Math.min(c|0,d.length));for(var e=b.length;0<e&&0<c;)if(d[--c]!=b[--e])return!1;return 0>=e}},"es6"); 
function ra(a,b){a instanceof String&&(a+="");var c=0,d=!1,e={next:function(){if(!d&&c<a.length){var f=c++;return{value:b(f,a[f]),done:!1}}d=!0;return{done:!0,value:void 0}}};e[u(r.Symbol,"iterator")]=function(){return e};return e}v("Array.prototype.entries",function(a){return a?a:function(){return ra(this,function(b,c){return[b,c]})}},"es6");v("Array.prototype.keys",function(a){return a?a:function(){return ra(this,function(b){return b})}},"es6");v("globalThis",function(a){return a||ja},"es_2020"); 
v("Object.values",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push(b[d]);return c}},"es8");v("Array.prototype.values",function(a){return a?a:function(){return ra(this,function(b,c){return c})}},"es8");v("Object.is",function(a){return a?a:function(b,c){return b===c?0!==b||1/b===1/c:b!==b&&c!==c}},"es6"); 
v("Array.prototype.includes",function(a){return a?a:function(b,c){var d=this;d instanceof String&&(d=String(d));var e=d.length;c=c||0;for(0>c&&(c=Math.max(c+e,0));c<e;c++){var f=d[c];if(f===b||u(Object,"is").call(Object,f,b))return!0}return!1}},"es7");v("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==qa(this,b,"includes").indexOf(b,c||0)}},"es6"); 
v("Object.entries",function(a){return a?a:function(b){var c=[],d;for(d in b)Object.prototype.hasOwnProperty.call(b,d)&&c.push([d,b[d]]);return c}},"es8");/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
var y=this||self;function sa(a){return a};function z(a){a=parseFloat(a);return isNaN(a)||1<a||0>a?0:a};function ta(a,b){this.m=a===ua&&b||"";this.g=va}var va={},ua={};function wa(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}};var xa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if("string"===typeof a)return"string"!==typeof b||1!=b.length?-1:a.indexOf(b,0);for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},ya=Array.prototype.some?function(a,b){return Array.prototype.some.call(a,b,void 0)}:function(a,b){for(var c=a.length,d="string"===typeof a?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a))return!0;return!1};var za,Aa;a:{for(var Da=["CLOSURE_FLAGS"],Ea=y,Fa=0;Fa<Da.length;Fa++)if(Ea=Ea[Da[Fa]],null==Ea){Aa=null;break a}Aa=Ea}var Ga=Aa&&Aa[610401301];za=null!=Ga?Ga:!1;function Ha(){var a=y.navigator;return a&&(a=a.userAgent)?a:""}var C,Ia=y.navigator;C=Ia?Ia.userAgentData||null:null;function Ja(a){return za?C?C.brands.some(function(b){return(b=b.brand)&&-1!=b.indexOf(a)}):!1:!1}function D(a){return-1!=Ha().indexOf(a)};function E(){return za?!!C&&0<C.brands.length:!1}function Ka(){return E()?Ja("Chromium"):(D("Chrome")||D("CriOS"))&&!(E()?0:D("Edge"))||D("Silk")};function La(a){La[" "](a);return a}La[" "]=function(){};var Ma;function Na(a){this.g=a}Na.prototype.toString=function(){return this.g+""};function Oa(a){return a instanceof Na&&a.constructor===Na?a.g:"type_error:TrustedResourceUrl"}var Pa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,Qa={};function Ra(a){if(void 0===Ma){var b=null;var c=y.trustedTypes;if(c&&c.createPolicy){try{b=c.createPolicy("goog#html",{createHTML:sa,createScript:sa,createScriptURL:sa})}catch(d){y.console&&y.console.error(d.message)}Ma=b}else Ma=b}a=(b=Ma)?b.createScriptURL(a):a;return new Na(a,Qa)} 
function Sa(a,b,c){if(null==c)return b;if("string"===typeof c)return c?a+encodeURIComponent(c):"";for(var d in c)if(Object.prototype.hasOwnProperty.call(c,d)){var e=c[d];e=Array.isArray(e)?e:[e];for(var f=0;f<e.length;f++){var g=e[f];null!=g&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(g)))}}return b};var Ta=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function Ua(a){var b=a.match(Ta);a=b[5];var c=b[6];b=b[7];var d="";a&&(d+=a);c&&(d+="?"+c);b&&(d+="#"+b);return d}function Va(a,b,c,d){for(var e=c.length;0<=(b=a.indexOf(c,b))&&b<d;){var f=a.charCodeAt(b-1);if(38==f||63==f)if(f=a.charCodeAt(b+e),!f||61==f||38==f||35==f)return b;b+=e+1}return-1}var Wa=/#|$/; 
function F(a,b){var c=a.search(Wa),d=Va(a,0,b,c);if(0>d)return null;var e=a.indexOf("&",d);if(0>e||e>c)e=c;d+=b.length+1;return decodeURIComponent(a.slice(d,-1!==e?e:0).replace(/\+/g," "))}var Xa=/[?&]($|#)/; 
function G(a,b,c){for(var d=a.search(Wa),e=0,f,g=[];0<=(f=Va(a,e,b,d));)g.push(a.substring(e,f)),e=Math.min(a.indexOf("&",f)+1||d,d);g.push(a.slice(e));a=g.join("").replace(Xa,"$1");c=null!=c?"="+encodeURIComponent(String(c)):"";(b+=c)?(c=a.indexOf("#"),0>c&&(c=a.length),d=a.indexOf("?"),0>d||d>c?(d=c,e=""):e=a.substring(d+1,c),c=[a.slice(0,d),e,a.slice(c)],a=c[1],c[1]=b?a?a+"&"+b:b:a,b=c[0]+(c[1]?"?"+c[1]:"")+c[2]):b=a;return b};/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function Ya(a,b){a.src=Oa(b);var c,d;(c=(b=null==(d=(c=(a.ownerDocument&&a.ownerDocument.defaultView||window).document).querySelector)?void 0:d.call(c,"script[nonce]"))?b.nonce||b.getAttribute("nonce")||"":"")&&a.setAttribute("nonce",c)};function Za(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{La(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function $a(){if(!r.globalThis.crypto)return Math.random();try{var a=new Uint32Array(1);r.globalThis.crypto.getRandomValues(a);return a[0]/65536/65536}catch(b){return Math.random()}}function ab(a,b){if(a)for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(a[c],c,a)} 
var cb=wa(function(){return ya(["Google Web Preview","Mediapartners-Google","Google-Read-Aloud","Google-Adwords"],bb)||1E-4>Math.random()}),db=wa(function(){return bb("MSIE")});function bb(a){return-1!=Ha().indexOf(a)}function H(a){return/^true$/.test(a)}function eb(a,b){if(!a||!b.head)return null;var c=fb("META");b.head.appendChild(c);c.httpEquiv="origin-trial";c.content=a;return c}function fb(a,b){b=void 0===b?document:b;return b.createElement(String(a).toLowerCase())};var gb=z("0.20"),hb=z("0.002"),ib=z("1.0"),jb=z("0.00"),kb=z("0.00"),lb=z("0.00"),nb=H("true"),ob=H("true"),pb=H("true"),qb=H("true"),rb=H("true");var sb=null;function tb(){if(null===sb){sb="";try{var a="";try{a=y.top.location.hash}catch(c){a=y.location.hash}if(a){var b=a.match(/\bdeid=([\d,]+)/);sb=b?b[1]:""}}catch(c){}}return sb} 
function I(a,b,c){var d=J;if(c?d.g.hasOwnProperty(c)&&""==d.g[c]:1){var e;e=(e=tb())?(e=e.match(new RegExp("\\b("+a.join("|")+")\\b")))?e[0]:null:null;if(e)a=e;else a:{if(!db()&&!cb()&&(e=Math.random(),e<b)){e=$a();a=a[Math.floor(e*a.length)];break a}a=null}a&&""!=a&&(c?d.g.hasOwnProperty(c)&&(d.g[c]=a):d.m[a]=!0)}}function K(a){var b=J;return b.g.hasOwnProperty(a)?b.g[a]:""}function ub(){var a=J,b=[];ab(a.m,function(c,d){b.push(d)});ab(a.g,function(c){""!=c&&b.push(c)});return b};var vb={K:2,S:13,R:14,N:16,M:17,L:18,J:19,U:20,T:21,I:22},J=null;function wb(){return!!J&&("466465926"==K(20)||"466465925"==K(20))}function xb(){return!!J&&"592230571"==K(16)}function yb(){return!!J&&("512247839"==K(22)||"512247838"==K(22))};function zb(a){var b=void 0===b?y:b;var c,d;return(null==(c=b.performance)?void 0:null==(d=c.timing)?void 0:d[a])||0};function M(a){var b="o";if(a.o&&a.hasOwnProperty(b))return a.o;b=new a;return a.o=b};var Ab={O:0,F:1,P:2,H:3,G:4};function Bb(){this.g={}}function Cb(a,b,c){"number"===typeof c&&0<c&&(a.g[b]=Math.round(c))}function Db(a){var b=M(Bb);var c=void 0===c?y:c;c=c.performance;Cb(b,a,c&&c.now?c.now():null)}function Eb(){function a(){return Cb(b,0,zb("loadEventStart")-zb("navigationStart"))}var b=M(Bb);0!=zb("loadEventStart")?a():window.addEventListener("load",a)}function Fb(a,b){b.google_tag_manager&&b.google_tag_manager._li&&(b=b.google_tag_manager._li,Cb(a,4,b.cbt),Cb(a,3,b.cst))} 
function Gb(){var a=M(Bb);return u(Object,"values").call(Object,Ab).map(function(b){return[b,a.g[b]||0]})};var Hb=H("false");var Ib={};function N(a){Ib.TAGGING=Ib.TAGGING||[];Ib.TAGGING[a]=!0};function Jb(a){return"function"===typeof a}function Kb(a){return"string"===typeof a}var Lb=Array.isArray;function Mb(a,b){if(a&&Lb(a))for(var c=0;c<a.length;c++)if(a[c]&&b(a[c]))return a[c]}function Nb(a,b){for(var c in a)Object.prototype.hasOwnProperty.call(a,c)&&b(c,a[c])}function Ob(){return new Date(Date.now())};var O=window,P=document;function Pb(a,b){b&&(a.addEventListener?a.onload=b:a.onreadystatechange=function(){a.readyState in{loaded:1,complete:1}&&(a.onreadystatechange=null,b())})}var Qb={async:1,nonce:1,onerror:1,onload:1,src:1,type:1},Rb={onload:1,src:1,width:1,height:1,style:1};function Sb(a,b,c){b&&Nb(b,function(d,e){d=d.toLowerCase();c.hasOwnProperty(d)||a.setAttribute(d,e)})} 
function Tb(a,b,c,d){var e=P.createElement("script");Sb(e,c,Qb);e.type="text/javascript";e.async=c&&!1===c.async?!1:!0;a=Ra(null===a?"null":void 0===a?"undefined":a);Ya(e,a);Pb(e,b);d?d.appendChild(e):(b=P.getElementsByTagName("script")[0]||P.body||P.head,b.parentNode.insertBefore(e,b))} 
function Ub(a,b,c,d,e,f){f=void 0===f?!0:f;var g=e;e=!1;g||(g=P.createElement("iframe"),e=!0);Sb(g,c,Rb);d&&Nb(d,function(h,k){g.dataset[h]=k});f&&(g.height="0",g.width="0",g.style.display="none",g.style.visibility="hidden");e&&(c=P.body&&P.body.lastChild||P.body||P.head,c.parentNode.insertBefore(g,c));Pb(g,b);void 0!==a&&(g.src=a)};function Vb(){var a=void 0===a?document:a;var b;return!(null==(b=a.featurePolicy)||!(aa=b.allowedFeatures(),u(aa,"includes")).call(aa,"attribution-reporting"))};function Wb(a,b,c){a=Xb(a,!0);if(a[b])return!1;a[b]=[];a[b][0]=c;return!0}function Xb(a,b){var c=a.GooglebQhCsO;c||(c={},b&&(a.GooglebQhCsO=c));return c};!D("Android")||Ka();Ka();D("Safari")&&(Ka()||(E()?0:D("Coast"))||(E()?0:D("Opera"))||(E()?0:D("Edge"))||(E()?Ja("Microsoft Edge"):D("Edg/"))||E()&&Ja("Opera"));var Yb={},Zb=null; 
function $b(a){for(var b=[],c=0,d=0;d<a.length;d++){var e=a.charCodeAt(d);255<e&&(b[c++]=e&255,e>>=8);b[c++]=e}a=4;void 0===a&&(a=0);if(!Zb)for(Zb={},c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));Yb[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===Zb[h]&&(Zb[h]=g)}}a=Yb[a];c=Array(Math.floor(b.length/3));d=a[64]||"";for(e=f=0;f<b.length-2;f+=3){var k=b[f],m=b[f+1];h=b[f+2];g=a[k>>2];k=a[(k& 
3)<<4|m>>4];m=a[(m&15)<<2|h>>6];h=a[h&63];c[e++]=g+k+m+h}g=0;h=d;switch(b.length-f){case 2:g=b[f+1],h=a[(g&15)<<2]||d;case 1:b=b[f],c[e]=a[b>>2]+a[(b&3)<<4|g>>4]+h+d}return c.join("")};function ac(a,b,c,d,e){var f=F(c,"fmt");if(d){var g=F(c,"random"),h=F(c,"label")||"";if(!g)return!1;g=$b(decodeURIComponent(h.replace(/\+/g," "))+":"+decodeURIComponent(g.replace(/\+/g," ")));if(!Wb(a,g,d))return!1}f&&4!=f&&(c=G(c,"rfmt",f));c=G(c,"fmt",4);Tb(c,function(){a.google_noFurtherRedirects&&d&&d.call&&(a.google_noFurtherRedirects=null,d())},e,b.getElementsByTagName("script")[0].parentElement||void 0);return!0};var bc=new function(a,b){this.g=a;this.defaultValue=void 0===b?!1:b}(1933);function cc(){var a={};this.g=function(){var b=bc.g,c=bc.defaultValue;return null!=a[b]?a[b]:c}};var dc=[];function Q(a){return void 0==dc[a]?!1:dc[a]};var R={},ec={ad_storage:!1,ad_user_data:!1,ad_personalization:!1};function fc(){var a={};var b=O.google_tag_data;O.google_tag_data=void 0===b?a:b;a=O.google_tag_data;return a.ics=a.ics||new gc}function gc(){this.entries={};this.cps={};this.wasSetLate=this.accessedAny=this.accessedDefault=this.usedSetCps=this.usedImplicit=this.usedUpdate=this.usedDefault=this.usedDeclare=this.active=!1;this.g=[]}l=gc.prototype; 
l.default=function(a,b,c,d,e,f){this.usedDefault||!this.accessedDefault&&!this.accessedAny||(this.wasSetLate=!0);this.usedDefault=this.active=!0;N(19);void 0==b?N(18):hc(this,a,"granted"===b,c,d,e,f)};l.waitForUpdate=function(a,b){for(var c=0;c<a.length;c++)hc(this,a[c],void 0,void 0,"","",b)}; 
function hc(a,b,c,d,e,f,g){var h=u(a,"entries"),k=h[b]||{},m=k.region;d=d&&Kb(d)?d.toUpperCase():void 0;e=e.toUpperCase();f=f.toUpperCase();if(ic(d,m,e,f)){f=!!(g&&0<g&&void 0===k.update);var q={region:d,declare_region:k.declare_region,implicit:k.implicit,default:void 0!==c?c:k.default,declare:k.declare,update:k.update,quiet:f};if(""!==e||!1!==k.default)h[b]=q;f&&O.setTimeout(function(){if(h[b]===q&&q.quiet){q.quiet=!1;var p=[b];if(Q(4))for(var n in R)R.hasOwnProperty(n)&&R[n]===b&&p.push(n);for(n= 
0;n<p.length;n++)jc(a,p[n]);a.notifyListeners();N(2)}},g)}}l.update=function(a,b){this.usedDefault||this.usedUpdate||!this.accessedAny||(this.wasSetLate=!0);this.usedUpdate=this.active=!0;if(void 0!=b){var c=this.getConsentState(a),d=u(this,"entries");d=d[a]=d[a]||{};d.update="granted"===b;var e=this.getConsentState(a);b=[a];if(Q(4))for(var f in R)R.hasOwnProperty(f)&&R[f]===a&&b.push(f);if(d.quiet)for(d.quiet=!1,a=0;a<b.length;a++)jc(this,b[a]);else if(e!==c)for(a=0;a<b.length;a++)jc(this,b[a])}}; 
l.declare=function(a,b,c,d,e){this.usedDeclare=this.active=!0;var f=u(this,"entries"),g=f[a]||{},h=g.declare_region;c=c&&Kb(c)?c.toUpperCase():void 0;d=d.toUpperCase();e=e.toUpperCase();ic(c,h,d,e)&&(b={region:g.region,declare_region:c,declare:"granted"===b,implicit:g.implicit,default:g.default,update:g.update,quiet:g.quiet},""!==d||!1!==g.declare)&&(f[a]=b)};l.implicit=function(a,b){this.usedImplicit=!0;var c=u(this,"entries");a=c[a]=c[a]||{};!1!==a.implicit&&(a.implicit="granted"===b)}; 
l.getConsentState=function(a){var b=u(this,"entries"),c=b[a]||{},d=c.update;if(void 0!==d)return d?1:2;d=c.default;if(void 0!==d)return d?1:2;if(Q(4)&&R.hasOwnProperty(a)){b=b[R[a]]||{};d=b.update;if(void 0!==d)return d?1:2;d=b.default;if(void 0!==d)return d?1:2}d=c.declare;if(void 0!==d)return d?1:2;if(Q(3)){d=c.implicit;if(void 0!==d)return d?3:4;if(ec.hasOwnProperty(a))return ec[a]?3:4}return 0}; 
l.setCps=function(a,b,c,d,e){a:{var f=this.cps,g=f[a]||{},h=g.region;c=c&&Kb(c)?c.toUpperCase():void 0;d=d.toUpperCase();if(ic(c,h,d,e.toUpperCase())&&(b={enabled:"granted"===b,region:c},""!==d||!1!==g.enabled)){f[a]=b;a=!0;break a}a=!1}a&&(this.usedSetCps=!0)};l.addListener=function(a,b){this.g.push({consentTypes:a,A:b})};function jc(a,b){for(var c=0;c<a.g.length;++c){var d=a.g[c];Lb(d.consentTypes)&&-1!==d.consentTypes.indexOf(b)&&(d.v=!0)}} 
l.notifyListeners=function(a,b){for(var c=0;c<this.g.length;++c){var d=this.g[c];if(d.v){d.v=!1;try{d.A({consentEventId:a,consentPriorityId:b})}catch(e){}}}};function ic(a,b,c,d){return""===c||a===d?!0:a===c?b!==d:!a&&!b}function kc(a){var b=fc();b.accessedAny=!0;switch(b.getConsentState(a)){case 1:case 3:return!0;case 2:case 4:return!1;default:return!0}}function lc(a){var b=fc();b.accessedAny=!0;return!(u(b,"entries")[a]||{}).quiet}function mc(a,b){fc().addListener(a,b)} 
function nc(a){function b(){for(var e=0;e<c.length;e++)if(!lc(c[e]))return!0;return!1}var c=["ad_storage"];if(b()){var d=!1;mc(c,function(e){d||b()||(d=!0,a(e))})}else a({})} 
function oc(a){function b(){for(var g=[],h=0;h<d.length;h++){var k=d[h];kc(k)&&!e[k]&&g.push(k)}return g}function c(g){for(var h=0;h<g.length;h++)e[g[h]]=!0}var d=Kb("ad_storage")?["ad_storage"]:"ad_storage",e={},f=b();f.length!==d.length&&(c(f),mc(d,function(g){function h(q){0!==q.length&&(c(q),g.consentTypes=q,a(g))}var k=b();if(0!==k.length){var m=u(Object,"keys").call(Object,e).length;k.length+m>=d.length?h(k):O.setTimeout(function(){h(b())},500)}}))};function pc(a,b,c,d){if(qc(d)){d=[];b=String(b||rc()).split(";");for(var e=0;e<b.length;e++){var f=b[e].split("="),g=f[0].replace(/^\s*|\s*$/g,"");g&&g==a&&((f=f.slice(1).join("=").replace(/^\s*|\s*$/g,""))&&c&&(f=decodeURIComponent(f)),d.push(f))}a=d}else a=[];return a}function sc(a,b,c,d){var e=rc(),f=window;"null"!==f.origin&&(f.document.cookie=a);a=rc();return e!=a||void 0!=c&&0<=pc(b,a,!1,d).indexOf(c)} 
function tc(a,b,c){function d(p,n,w){if(null==w)return delete g[n],p;g[n]=w;return p+"; "+n+"="+w}function e(p,n){if(null==n)return delete g[n],p;g[n]=!0;return p+"; "+n}if(qc(c.i)){if(void 0==b)var f=a+"=deleted; expires="+(new Date(0)).toUTCString();else c.encode&&(b=encodeURIComponent(b)),b=uc(b),f=a+"="+b;var g={};f=d(f,"path",c.path);if(c.expires instanceof Date)var h=c.expires.toUTCString();else null!=c.expires&&(h=c.expires);f=d(f,"expires",h);f=d(f,"max-age",c.V);f=d(f,"samesite",c.W);c.X&& 
(f=e(f,"secure"));if((h=c.domain)&&"auto"===h.toLowerCase()){h=vc();for(var k=0;k<h.length;++k){var m="none"!==h[k]?h[k]:void 0,q=d(f,"domain",m);q=e(q,c.flags);if(!xc(m,c.path)&&sc(q,a,b,c.i))break}}else h&&"none"!==h.toLowerCase()&&(f=d(f,"domain",h)),f=e(f,c.flags),xc(h,c.path)||sc(f,a,b,c.i)}}function yc(a,b,c){null==c.path&&(c.path="/");c.domain||(c.domain="auto");tc(a,b,c)}function uc(a){a&&1200<a.length&&(a=a.substring(0,1200));return a}var zc=/^(www\.)?google(\.com?)?(\.[a-z]{2})?$/,Ac=/(^|\.)doubleclick\.net$/i; 
function xc(a,b){return Ac.test(window.document.location.hostname)||"/"===b&&zc.test(a)}function rc(){return"null"!==window.origin?window.document.cookie:""}function vc(){var a=[],b=window.document.location.hostname.split(".");if(4===b.length){var c=b[b.length-1];if(parseInt(c,10).toString()===c)return["none"]}for(c=b.length-2;0<=c;c--)a.push(b.slice(c).join("."));b=window.document.location.hostname;Ac.test(b)||zc.test(b)||a.push("none");return a} 
function qc(a){return a&&M(cc).g()?lc(a)?kc(a):!1:!0};function Bc(a,b){var c,d=Number(null!=a.u?a.u:void 0);0!==d&&(c=new Date((b||Ob().getTime())+1E3*(d||7776E3)));return{path:a.path,domain:a.domain,flags:a.flags,encode:!0,expires:c,i:void 0}};function Cc(a){var b=[],c=P.cookie.split(";");a=new RegExp("^\\s*"+(a||"_gac")+"_(UA-\\d+-\\d+)=\\s*(.+?)\\s*$");for(var d=0;d<c.length;d++){var e=c[d].match(a);e&&b.push({s:e[1],value:e[2],timestamp:Number(e[2].split(".")[1])||0})}b.sort(function(f,g){return g.timestamp-f.timestamp});return b} 
function S(a,b){a=Cc(a);var c={};if(!a||!a.length)return c;for(var d=0;d<a.length;d++){var e=a[d].value.split(".");if(!("1"!==e[0]||b&&3>e.length||!b&&3!==e.length)&&Number(e[1])){c[a[d].s]||(c[a[d].s]=[]);var f={version:e[0],timestamp:1E3*Number(e[1]),h:e[2]};b&&3<e.length&&(f.labels=e.slice(3));c[a[d].s].push(f)}}return c};var Dc=/:[0-9]+$/;function Ec(a,b){function c(f){return Q(10)?decodeURIComponent(f.replace(/\+/g," ")):decodeURIComponent(f).replace(/\+/g," ")}a=na(a.split("&"));for(var d=a.next();!d.done;d=a.next()){var e=na(d.value.split("="));d=e.next().value;e=oa(e);if(c(d)===b)return c(e.join("="))}} 
function Fc(a,b){var c="query";var d=(d=a.protocol)?d.replace(":","").toLowerCase():"";c&&(c=String(c).toLowerCase());switch(c){case "url_no_fragment":b="";a&&a.href&&(b=a.href.indexOf("#"),b=0>b?a.href:a.href.substr(0,b));a=b;break;case "protocol":a=d;break;case "host":a=a.hostname.replace(Dc,"").toLowerCase();break;case "port":a=String(Number(a.port)||("http"===d?80:"https"===d?443:""));break;case "path":a.pathname||a.hostname||N(1);a="/"===a.pathname.charAt(0)?a.pathname:"/"+a.pathname;a=a.split("/"); 
0<=[].indexOf(a[a.length-1])&&(a[a.length-1]="");a=a.join("/");break;case "query":a=a.search.replace("?","");b&&(a=Ec(a,b));break;case "extension":a=a.pathname.split(".");a=1<a.length?a[a.length-1]:"";a=a.split("/")[0];break;case "fragment":a=a.hash.replace("#","");break;default:a=a&&a.href}return a};var Gc=/^\w+$/,Hc=/^[\w-]+$/,Ic={aw:"_aw",dc:"_dc",gf:"_gf",ha:"_ha",gp:"_gp",gb:"_gb"};function T(){return M(cc).g()?kc("ad_storage"):!0}function Jc(a,b){lc("ad_storage")?T()?a():oc(a):b?N(3):nc(function(){Jc(a,!0)})}function Kc(a){return Lc(a).map(function(b){return b.h})} 
function Lc(a){var b=[];if("null"===O.origin||!P.cookie)return b;a=pc(a,P.cookie,void 0,"ad_storage");if(!a||0==a.length)return b;for(var c={},d=0;d<a.length;c={h:c.h},d++){var e=Mc(a[d]);if(null!=e){var f=e;e=f.version;c.h=f.h;var g=f.timestamp;f=f.labels;var h=Mb(b,function(k){return function(m){return m.h===k.h}}(c));h?(h.timestamp=Math.max(h.timestamp,g),h.labels=Nc(h.labels,f||[])):b.push({version:e,h:c.h,timestamp:g,labels:f})}}b.sort(function(k,m){return m.timestamp-k.timestamp});return Oc(b)} 
function Nc(a,b){for(var c={},d=[],e=0;e<a.length;e++)c[a[e]]=!0,d.push(a[e]);for(a=0;a<b.length;a++)c[b[a]]||d.push(b[a]);return d}function Pc(a){return a&&"string"==typeof a&&a.match(Gc)?a:"_gcl"} 
function Qc(){var a=O.location.href,b=P.createElement("a");a&&(b.href=a);var c=b.pathname;"/"!==c[0]&&(a||N(1),c="/"+c);a=b.hostname.replace(Dc,"");var d={href:b.href,protocol:b.protocol,host:b.host,hostname:a,pathname:c,search:b.search,hash:b.hash,port:b.port};b=Fc(d,"gclid");c=Fc(d,"gclsrc");a=Fc(d,"wbraid");var e=Fc(d,"dclid");b&&c&&a||(d=d.hash.replace("#",""),b=b||Ec(d,"gclid"),c=c||Ec(d,"gclsrc"),a=a||Ec(d,"wbraid"));return Rc(b,c,e,a)} 
function Rc(a,b,c,d){function e(g,h){f[h]||(f[h]=[]);f[h].push(g)}var f={};f.gclid=a;f.gclsrc=b;f.dclid=c;void 0!==d&&Hc.test(d)&&(f.gbraid=d,e(d,"gb"));if(void 0!==a&&a.match(Hc))switch(b){case void 0:e(a,"aw");break;case "aw.ds":e(a,"aw");e(a,"dc");break;case "ds":e(a,"dc");break;case "3p.ds":e(a,"dc");break;case "gf":e(a,"gf");break;case "ha":e(a,"ha")}c&&e(c,"dc");return f}function Sc(){var a={},b=Qc();Jc(function(){Tc(b,!1,a)})} 
function Tc(a,b,c,d,e){function f(p){p=["GCL",q,p];0<e.length&&p.push(e.join("."));return p.join(".")}function g(p,n){if(p=Uc(p,h))yc(p,n,k),m=!0}c=c||{};e=e||[];var h=Pc(c.prefix);d=d||Ob().getTime();var k=Bc(c,d);k.i="ad_storage";var m=!1,q=Math.round(d/1E3);a.aw&&g("aw",f(a.aw[0]));a.dc&&g("dc",f(a.dc[0]));a.gf&&g("gf",f(a.gf[0]));a.ha&&g("ha",f(a.ha[0]));a.gp&&g("gp",f(a.gp[0]));if(!m&&a.gb){a=a.gb[0];d=Uc("gb",h);c=!1;if(!b)for(b=Lc(d),d=0;d<b.length;d++)b[d].h===a&&b[d].labels&&0<b[d].labels.length&& 
(c=!0);c||g("gb",f(a))}}function Uc(a,b){a=Ic[a];if(void 0!==a)return b+a}function Vc(a){return 0!==Wc(a.split(".")).length?1E3*(Number(a.split(".")[1])||0):0}function Mc(a){a=Wc(a.split("."));return 0===a.length?null:{version:a[0],h:a[2],timestamp:1E3*(Number(a[1])||0),labels:a.slice(3)}}function Wc(a){return 3>a.length||"GCL"!==a[0]&&"1"!==a[0]||!/^\d+$/.test(a[1])||!Hc.test(a[2])?[]:a}function Oc(a){return a.filter(function(b){return Hc.test(b.h)})} 
function Xc(){var a=["aw"],b={};if("null"!==O.origin){for(var c=Pc(b.prefix),d={},e=0;e<a.length;e++)Ic[a[e]]&&(d[a[e]]=Ic[a[e]]);Jc(function(){Nb(d,function(f,g){g=pc(c+g,P.cookie,void 0,"ad_storage");g.sort(function(q,p){return Vc(p)-Vc(q)});if(g.length){var h=g[0];g=Vc(h);var k=0!==Wc(h.split(".")).length?h.split(".").slice(3):[],m={};h=0!==Wc(h.split(".")).length?h.split(".")[2]:void 0;m[f]=[h];Tc(m,!0,b,g,k)}})})}} 
function Yc(a,b,c,d){var e=[];c=c||{};if(!T())return e;var f=Lc(a);if(!f.length)return e;for(var g=0;g<f.length;g++)-1===(f[g].labels||[]).indexOf(b)?e.push(0):e.push(1);if(d)return e;1!==e[0]&&(d=f[0],f=f[0].timestamp,b=[d.version,Math.round(f/1E3),d.h].concat(d.labels||[],[b]).join("."),c=Bc(c,f),c.i="ad_storage",yc(a,b,c));return e}function Zc(a,b){b=Pc(b);a=Uc(a,b);if(!a)return 0;a=Lc(a);for(var c=b=0;c<a.length;c++)b=Math.max(b,a[c].timestamp);return b} 
function $c(a){var b=0,c;for(c in a)for(var d=a[c],e=0;e<d.length;e++)b=Math.max(b,Number(d[e].timestamp));return b};var ad=RegExp("^UA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*(?:%3BUA-\\d+-\\d+%3A[\\w-]+(?:%2C[\\w-]+)*)*$"),bd=/^~?[\w-]+(?:\.~?[\w-]+)*$/,cd=/^\d+\.fls\.doubleclick\.net$/,dd=/;gac=([^;?]+)/,ed=/;gacgb=([^;?]+)/,fd=/;gclaw=([^;?]+)/,gd=/;gclgb=([^;?]+)/; 
function hd(a,b,c){if(cd.test(a.location.host))return(b=a.location.href.match(c))&&2==b.length&&b[1].match(ad)?decodeURIComponent(b[1]):"";a=[];for(var d in b){c=[];for(var e=b[d],f=0;f<e.length;f++)c.push(e[f].h);a.push(d+":"+c.join(","))}return 0<a.length?a.join(";"):""}function id(a,b,c,d){var e=T()?S("_gac_gb",!0):{},f=[],g=!1,h;for(h in e){var k=Yc("_gac_gb_"+h,b,c,d);g=g||0!==k.length&&k.some(function(m){return 1===m});f.push(h+":"+k.join(","))}return{C:g?f.join(";"):"",B:hd(a,e,ed)}} 
function jd(a,b,c,d){if(cd.test(a.location.host)){if((a=a.location.href.match(d))&&2==a.length&&a[1].match(bd))return[{h:a[1]}]}else return Lc((b||"_gcl")+c);return[]}function kd(a,b){return jd(a,b,"_aw",fd).map(function(c){return c.h}).join(".")}function ld(a,b){return jd(a,b,"_gb",gd).map(function(c){return c.h}).join(".")}function md(a,b){var c=""!==ld(a,b)||0<u(Object,"keys").call(Object,T()?S("_gac_gb",!0):{}).length;a=""!==kd(a,b)||""!==hd(a,T()?S():{},dd);return c&&a} 
function nd(a){0!==Kc("_gcl_aw").length||a&&0!==Kc(a+"_aw").length||(Sc(),Xc())}function od(a,b,c){a=Yc((b&&b.prefix||"_gcl")+"_gb",a,b,c);return 0===a.length||a.every(function(d){return 0===d})?"":a.join(".")};function pd(){if(Jb(O.__uspapi)){var a="";try{O.__uspapi("getUSPData",1,function(b,c){c&&b&&(b=b.uspString)&&RegExp("^[\\da-zA-Z-]{1,20}$").test(b)&&(a=b)})}catch(b){}return a}};var qd="platform platformVersion architecture model uaFullVersion bitness fullVersionList wow64".split(" ");function rd(a){var b;return null!=(b=a.google_tag_data)?b:a.google_tag_data={}}function sd(a){a=a.google_tag_data;if(null!=a&&a.uach){a=a.uach;var b=u(Object,"assign").call(Object,{},a);a.fullVersionList&&(b.fullVersionList=a.fullVersionList.slice(0));a=b}else a=null;return a} 
function td(a){var b,c;return"function"===typeof(null==(b=a.navigator)?void 0:null==(c=b.userAgentData)?void 0:c.getHighEntropyValues)}function ud(){var a=window;if(td(a)){var b=rd(a);b.uach_promise||(a=a.navigator.userAgentData.getHighEntropyValues(qd).then(function(c){null!=b.uach||(b.uach=c);return c}),b.uach_promise=a)}};var vd={id:!0,origin:!0,destination:!0,start_date:!0,end_date:!0,location_id:!0},wd=/^[a-zA-Z0-9_]+$/,xd=!1,yd="google_conversion_id google_conversion_format google_conversion_type google_conversion_order_id google_conversion_language google_conversion_value google_conversion_currency google_conversion_domain google_conversion_label google_conversion_color google_disable_viewthrough google_enable_display_cookie_match google_gtag_event_data google_remarketing_only google_conversion_linker google_tag_for_child_directed_treatment google_tag_for_under_age_of_consent google_allow_ad_personalization_signals google_restricted_data_processing google_conversion_items google_conversion_merchant_id google_user_id google_custom_params google_conversion_date google_conversion_time google_conversion_js_version onload_callback opt_image_generator google_gtm_url_processor google_conversion_page_url google_conversion_referrer_url google_gcl_cookie_prefix google_gcl_cookie_path google_gcl_cookie_flags google_gcl_cookie_domain google_gcl_cookie_max_age_seconds google_read_gcl_cookie_opt_out google_basket_feed_country google_basket_feed_language google_basket_discount google_basket_transaction_type google_additional_conversion_params google_additional_params google_transport_url google_gtm_experiments".split(" "); 
function zd(a,b){var c=a;return function(){--c;0>=c&&b()}}function W(a){return null!=a?encodeURIComponent(String(a)):""}function Ad(a){if(null!=a){a=String(a).substring(0,512);var b=a.indexOf("#");return-1==b?a:a.substring(0,b)}return""}function X(a,b){b=W(b);return""!=b&&(a=W(a),""!=a)?"&".concat(a,"=",b):""}function Bd(a){var b=typeof a;return null==a||"object"==b||"function"==b?null:String(a).replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/=/g,"\\=")} 
function Cd(a){if(!a||"object"!=typeof a||"function"==typeof a.join)return"";var b=[],c;for(c in a)if(Object.prototype.hasOwnProperty.call(a,c)){var d=a[c];if(d&&"function"===typeof d.join){for(var e=[],f=0;f<d.length;++f){var g=Bd(d[f]);null!=g&&e.push(g)}d=0==e.length?null:e.join(",")}else d=Bd(d);(e=Bd(c))&&null!=d&&b.push(e+"="+d)}return b.join(";")}function Dd(a){return"number"!=typeof a&&"string"!=typeof a?"":W(a.toString())} 
function Ed(a,b){if(b.google_read_gcl_cookie_opt_out||b.google_remarketing_only||b.google_conversion_domain&&(!b.google_gcl_cookie_prefix||!/^_ycl/.test(b.google_gcl_cookie_prefix)))return"";var c="",d=Fd(b),e={};b.google_gcl_cookie_domain&&(e.domain=b.google_gcl_cookie_domain);b.google_gcl_cookie_flags&&(e.flags=b.google_gcl_cookie_flags);null!=b.google_gcl_cookie_max_age_seconds&&(e.u=b.google_gcl_cookie_max_age_seconds);b.google_gcl_cookie_path&&(e.path=b.google_gcl_cookie_path);d&&(e.prefix=d); 
if(Gd(b)&&b.j)var f=void 0===b.l;else cd.test(a.location.host)?f=!(fd.test(a.location.href)||dd.test(a.location.href)):(f=Math.max(Zc("aw",d),$c(T()?S():{})),f=Math.max(Zc("gb",d),$c(T()?S("_gac_gb",!0):{}))>f);if(f){if(void 0!==b.l)return b.l;c=ld(a,d||void 0);f=b.google_conversion_label;var g=od(f,e,b.j);c=X("gclgb",c)+(g?X("mcov",g):"");if(d)return b.l=c;d=id(a,f,e,b.j);a=d.B;d=d.C;c+=(a?X("gacgb",a):"")+(d?X("gacmcov",d):"");return b.l=c}if(d)return b=kd(a,d),X("gclaw",b);(b=kd(a))&&(c=X("gclaw", 
b));b=hd(a,T()?S():{},dd);return c+(b?X("gac",b):"")}function Hd(a){function b(d){try{return decodeURIComponent(d),!0}catch(e){return!1}}a=a?a.title:"";if(void 0==a||""==a)return"";a=encodeURIComponent(a);for(var c=256;!b(a.substr(0,c));)c--;return"&tiba="+a.substr(0,c)} 
function Id(a,b,c,d,e,f){var g="https://",h="landing"===d.google_conversion_type?"/extclk":"/";switch(e){default:return"";case 2:case 3:var k="googleads.g.doubleclick.net/";var m="pagead/viewthroughconversion/";break;case 1:k="www.google.com/";m="pagead/1p-conversion/";break;case 6:k="www.google.com/";m="ccm/conversion/";break;case 0:k=d.google_conversion_domain||"www.googleadservices.com/";m="pagead/conversion/";break;case 5:k=d.google_conversion_domain||"www.googleadservices.com/";m="ccm/conversion/"; 
break;case 4:k=(k=d.google_gtm_experiments)&&k.apcm?"www.google.com":k&&k.capiorig?d.google_conversion_id+".privacysandbox.googleadservices.com":"www.google.com/";m="pagead/privacysandbox/conversion/";break;case 7:k="googleads.g.doubleclick.net/",m="td/rul/"}nb&&d.google_transport_url&&(k=d.google_transport_url);"/"!==k[k.length-1]&&(k+="/");if(0===k.indexOf("http://")||0===k.indexOf("https://"))g="";g=[g,k,m,W(d.google_conversion_id),h,"?random=",W(d.google_conversion_time)].join("");h=X("cv",d.google_conversion_js_version); 
k=X("fst",d.google_conversion_first_time);m=X("num",d.google_conversion_snippets);var q=X("fmt",d.google_conversion_format),p=d.google_remarketing_only?X("userId",d.google_user_id):"";var n=d.google_tag_for_child_directed_treatment;n=null==n||0!==n&&1!==n?"":X("tfcd",n);var w=d.google_tag_for_under_age_of_consent;w=null==w||0!==w&&1!==w?"":X("tfua",w);var ca=d.google_allow_ad_personalization_signals;ca=!1===ca?X("npa",1):!0===ca?X("npa",0):"";var Ba=d.google_restricted_data_processing;Ba=pb?!0=== 
Ba?X("rdp",1):!1===Ba?X("rdp",0):"":"";var Ud=X("value",d.google_conversion_value),Vd=X("currency_code",d.google_conversion_currency),Wd=X("label",d.google_conversion_label),Xd=X("oid",d.google_conversion_order_id),Yd=X("bg",d.google_conversion_color);a:{var B=d.google_conversion_language;if(null!=B){B=B.toString();if(2==B.length){B=X("hl",B);break a}if(5==B.length){B=X("hl",B.substring(0,2))+X("gl",B.substring(3,5));break a}}B=""}var Zd=X("guid","ON"),$d=!d.google_conversion_domain&&"GooglemKTybQhCsO"in 
y&&"function"==typeof y.GooglemKTybQhCsO?X("resp","GooglemKTybQhCsO"):"",ae=X("disvt",d.google_disable_viewthrough),be=X("eid",ub().join());var da=d.google_conversion_date;var A=[];if(a){var L=a.screen;L&&(A.push(X("u_h",L.height)),A.push(X("u_w",L.width)),A.push(X("u_ah",L.availHeight)),A.push(X("u_aw",L.availWidth)),A.push(X("u_cd",L.colorDepth)));a.history&&A.push(X("u_his",a.history.length))}da&&"function"==typeof da.getTimezoneOffset&&A.push(X("u_tz",-da.getTimezoneOffset()));b&&("function"== 
typeof b.javaEnabled&&A.push(X("u_java",b.javaEnabled())),b.plugins&&A.push(X("u_nplug",b.plugins.length)),b.mimeTypes&&A.push(X("u_nmime",b.mimeTypes.length)));da=A.join("");b=b&&b.sendBeacon?X("sendb","1"):"";A=Jd();L=X("ig",/googleadservices\.com/.test("www.googleadservices.com")?1:0);var Ca=Cd(d.google_custom_params);f=Cd(f);f=Ca.concat(0<Ca.length&&0<f.length?";":"",f);f=""==f?"":"&".concat("data=",encodeURIComponent(f));Ca=Ed(c,d);var ea=d.google_conversion_page_url,de=d.google_conversion_referrer_url, 
fa="";if(c){var U=a.top==a?0:(U=a.location.ancestorOrigins)?U[U.length-1]==a.location.origin?1:2:Za(a.top)?1:2;ea=ea?ea:1==U?a.top.location.href:a.location.href;var wc="";J&&I(["509562772","509562773"],jb,21);if(J&&("509562773"==K(21)||"509562772"==K(21))){for(var x,t=a,V=t;t&&t!=t.parent;)t=t.parent,Za(t)&&(V=t);x=V;t=x.location.href;if(x===x.top)t={url:t,D:!0};else{V=!1;var mb=x.document;mb&&mb.referrer&&(t=mb.referrer,x.parent===x.top&&(V=!0));(x=x.location.ancestorOrigins)&&(x=x[x.length-1])&& 
-1===t.indexOf(x)&&(V=!1,t=x);t={url:t,D:V}}t.url&&ea!==t.url&&(wc=t.url)}fa+=X("frm",U);fa+=X("url",Ad(ea));fa+=X("ref",Ad(de||c.referrer));fa+=X("top",Ad(wc))}a=[h,k,m,q,p,n,w,ca,Ba,Ud,Vd,Wd,Xd,Yd,B,Zd,$d,ae,be,da,b,A,L,f,Ca,fa,Hd(c),Kd(d.google_additional_params),Kd(d.google_remarketing_only?{}:d.google_additional_conversion_params),"&hn="+W("www.googleadservices.com"),Ld(a),Md(a)].join("");c=tb();a+=0<c.length?"&debug_experiment_id="+c:"";if(!d.google_remarketing_only&&!d.google_conversion_domain){c= 
[X("mid",d.google_conversion_merchant_id),X("fcntr",d.google_basket_feed_country),X("flng",d.google_basket_feed_language),X("dscnt",d.google_basket_discount),X("bttype",d.google_basket_transaction_type)].join("");if(d)if(h=d.google_conversion_items){k=[];m=0;for(q=h.length;m<q;m++)p=h[m],n=[],p&&(n.push(Dd(p.value)),n.push(Dd(p.quantity)),n.push(Dd(p.item_id)),n.push(Dd(p.start_date)),n.push(Dd(p.end_date)),k.push("("+n.join("*")+")"));h=0<k.length?"&item="+k.join(""):""}else h="";else h="";c=[a, 
c,h].join("");a=4E3<c.length?[a,X("item","elngth")].join(""):c}g+=a;1===e||6===e?g+=[X("gcp",1),X("sscte",1),X("ct_cookie_present",1)].join(""):3==e&&(g+=X("gcp",1),g+=X("ct_cookie_present",1));ob&&(e=pd(),void 0!==e&&(g+=X("us_privacy",e||"error")));Gd(d)&&(g=d.j?g+X("gbcov",1):g+X("gbcov",0));return g} 
function Nd(a){if(!Hb){var b=document;var c="IFRAME";"application/xhtml+xml"===b.contentType&&(c=c.toLowerCase());c=b.createElement(c);c.style.display="none";c.src="https://bid.g.doubleclick.net/xbbe/pixel?d=KAE";a.body.appendChild(c)}}function Od(){return new Image} 
function Pd(a,b,c,d,e,f){var g=c.onload_callback;e=e&&g&&g.call?g:function(){};J&&I(["512247838","512247839"],rb?1:0,22);d+=X("async","1");g=c.google_gtm_url_processor;Jb(g)&&(d=g(d));var h=(g=c.opt_image_generator)&&g.call,k=yb()?{attributionsrc:""}:void 0;if(!(f=h||!f)){if(c.google_conversion_domain)var m=!1;else try{m=ac(a,b,d,e,k)}catch(q){m=!1}f=!m}f&&(a=Od,h&&(a=g),a=a(),a.src=d,yb()&&a.setAttribute("attributionsrc",""),a.onload=e)} 
function Qd(a,b){J&&"376635471"==K(2)&&("complete"===b.readyState?Nd(b):a.addEventListener?a.addEventListener("load",function(){Nd(b)}):a.attachEvent("onload",function(){Nd(b)}))} 
function Rd(a){if("landing"===a.google_conversion_type||!a.google_conversion_id||a.google_remarketing_only&&a.google_disable_viewthrough)return!1;a.google_conversion_date=new Date;a.google_conversion_time=a.google_conversion_date.getTime();a.google_conversion_snippets="number"===typeof a.google_conversion_snippets&&0<a.google_conversion_snippets?a.google_conversion_snippets+1:1;void 0===a.google_conversion_first_time&&(a.google_conversion_first_time=a.google_conversion_time);a.google_conversion_js_version= 
"9";0!=a.google_conversion_format&&1!=a.google_conversion_format&&2!=a.google_conversion_format&&3!=a.google_conversion_format&&(a.google_conversion_format=3);!1!==a.google_enable_display_cookie_match&&(a.google_enable_display_cookie_match=!0);return!0}function Sd(a,b){function c(f){d[f]=b&&null!=b[f]?b[f]:a[f]}for(var d={},e=0;e<yd.length;e++)c(yd[e]);c("onload_callback");return d} 
function Td(a){for(var b={},c=0;c<a.length;c++){var d=a[c],e=void 0;d.hasOwnProperty("google_business_vertical")?(e=d.google_business_vertical,b[e]=b[e]||{google_business_vertical:e}):(e="",Object.prototype.hasOwnProperty.call(b,e)||(b[e]={}));e=b[e];for(var f=u(Object,"keys").call(Object,d).filter(function(k){return vd.hasOwnProperty(k)}),g=0;g<f.length;g++){var h=f[g];h in e||(e[h]=[]);e[h].push(d[h])}}return u(Object,"values").call(Object,b)} 
function Jd(){var a="";xb()&&(a=Gb().map(function(b){return b.join("-")}).join("_"));return X("li",a)}function Ld(a){if(!qb||!a.__gsaExp||!a.__gsaExp.id)return"";a=a.__gsaExp.id;if(!Jb(a))return"";try{var b=Number(a());return isNaN(b)?"":X("gsaexp",b)}catch(c){return""}} 
function Md(a){function b(d,e){null!=e&&c.push(d+"="+encodeURIComponent(e))}if(!wb())return"";a=sd(a);if(!a)return"";var c=[];b("&uaa",a.architecture);b("&uab",a.bitness);b("&uam",a.model);b("&uap",a.platform);b("&uapv",a.platformVersion);null!=a.wow64&&b("&uaw",a.wow64?"1":"0");a.fullVersionList&&b("&uafvl",a.fullVersionList.map(function(d){return encodeURIComponent(d.brand||"")+";"+encodeURIComponent(d.version||"")}).join("|"));return c.join("")} 
function Kd(a){if(!a)return"";var b="",c;for(c in a)a.hasOwnProperty(c)&&(b+=X(c,a[c]));return b}function Gd(a){return(a=a.google_gtm_experiments)&&a.gbcov?!0:!1}function Fd(a){return a.google_gcl_cookie_prefix&&"_gcl"!==a.google_gcl_cookie_prefix&&wd.test(a.google_gcl_cookie_prefix)?a.google_gcl_cookie_prefix:""} 
function ce(a,b){if(!b.google_remarketing_only&&ee(a,b)){a=b.google_additional_conversion_params||{};var c=b.google_gtm_experiments;a.capi=c&&c.apcm?"2":"1";b.google_additional_conversion_params=a}} 
function ee(a,b){if(b.google_transport_url)return!1;if((b=b.google_gtm_experiments)&&b.apcm)return!0;if(!b||!b.capi)return!1;a:{if(!xd){eb("A4w7HyCK6tScR/6oxyP31X0MsYLu0ZlIdOBV/7GEXwRIQZy3/qaAa0jm3+mKd8mQDUB6svQWIUC2X/gyNdSvbgAAAACUeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJBdHRyaWJ1dGlvblJlcG9ydGluZ0Nyb3NzQXBwV2ViIiwiZXhwaXJ5IjoxNzA3MjYzOTk5LCJpc1N1YmRvbWFpbiI6dHJ1ZSwiaXNUaGlyZFBhcnR5Ijp0cnVlfQ\x3d\x3d",a);if(!Vb()&&!eb(fe()?"":"A2kc5o2ErHAbqJvF2MHSdYtnc2Bp3n6Jn2kNeko6SgHH6zXBHn0+4BbAW2No9ylVJMkzJAPwMqCVHqXm+IF1DgQAAACKeyJvcmlnaW4iOiJodHRwczovL2dvb2dsZWFkc2VydmljZXMuY29tOjQ0MyIsImZlYXR1cmUiOiJQcml2YWN5U2FuZGJveEFkc0FQSXMiLCJleHBpcnkiOjE2OTUxNjc5OTksImlzU3ViZG9tYWluIjp0cnVlLCJpc1RoaXJkUGFydHkiOnRydWV9",a)){a=!1;break a}xd=!0}a=Vb()}return a} 
function ge(a,b,c,d,e){a=Id(a,b,c,d,7,e);b="AW-"+d.google_conversion_id;(d=d.google_conversion_label)&&(b=b+"/"+d);a:{d=b;b=void 0;try{b=P.querySelector('iframe[data-tagging-id="'+d+'"]')}catch(f){}if(b){if((c=Number(b.dataset.loadTime))&&6E4>Ob().getTime()-c){N(9);break a}}else try{if(50<=P.querySelectorAll('iframe[allow="join-ad-interest-group"][data-tagging-id*="-"]').length){N(10);break a}}catch(f){}Ub(a,void 0,{allow:"join-ad-interest-group"},{taggingId:d,loadTime:Ob().getTime()},b)}} 
function fe(){return!!u("www.googleadservices.com","endsWith").call("www.googleadservices.com","google.com")};var he=!1,ie=document.currentScript&&document.currentScript.src||""; 
function je(a,b,c){try{if(!he&&(he=!0,!c.google_gtm)){var d=void 0,e=void 0,f=F(a.location.href,"gtm_debug");ke(f)&&(d=2);d||0!==b.referrer.indexOf("https://tagassistant.google.com/")||(d=3);!d&&0<=xa(b.cookie.split("; "),"__TAG_ASSISTANT=x")&&(d=4);d||(e=b.documentElement.getAttribute("data-tag-assistant-present"),ke(e)&&(d=5));if(d){var g="AW-"+(c.google_conversion_id||"");if(!a["google.tagmanager.debugui2.queue"]){a["google.tagmanager.debugui2.queue"]=[];var h=new ta(ua,"https://www.googletagmanager.com/debug/bootstrap"); 
var k=Ra(h instanceof ta&&h.constructor===ta&&h.g===va?h.m:"type_error:Const");c={id:g,src:"LEGACY",cond:d};var m=Pa.exec(Oa(k).toString()),q=m[3]||"";var p=Ra(m[1]+Sa("?",m[2]||"",c)+Sa("#",q));var n=fb("SCRIPT",b);Ya(n,p);var w=b.getElementsByTagName("script")[0];w&&w.parentNode&&w.parentNode.insertBefore(n,w)}a["google.tagmanager.debugui2.queue"].push({messageType:"LEGACY_CONTAINER_STARTING",data:{id:g,scriptSource:ie}})}}}catch(ca){}} 
function ke(a){if(null==a||0===a.length)return!1;a=Number(a);var b=Date.now();return a<b+3E5&&a>b-9E5};function le(a,b){a.onload_callback=a.onload_callback&&"function"==typeof a.onload_callback.call?zd(b,a.onload_callback):function(){}} 
function me(a,b,c,d){je(a,c,d);xb()&&(Db(2),d.google_gtm&&Fb(M(Bb),a));var e=!1;if(3!=d.google_conversion_format)return!1;try{if(Rd(d)){d.google_remarketing_only&&d.google_enable_display_cookie_match&&!Hb&&J&&I(["376635470","376635471"],gb,2);d.google_remarketing_only&&!d.google_conversion_domain&&J&&I(["759238990","759238991"],lb,13);!d.google_remarketing_only||d.google_conversion_domain||J&&("759248991"==K(14)||"759248990"==K(14))||J&&I(["759248990","759248991"],kb,14);!1!==d.google_conversion_linker&& 
(d.google_gtm||nd(d.google_gcl_cookie_prefix));if(1==d.google_remarketing_only&&null!=d.google_gtag_event_data&&null!=d.google_gtag_event_data.items&&d.google_gtag_event_data.items.constructor===Array&&0<d.google_gtag_event_data.items.length)ne(a,b,c,d);else{var f=d.google_gtm_experiments&&d.google_gtm_experiments.ccmpp;if(d.google_conversion_domain||d.google_transport_url&&"https://pagead2.googlesyndication.com/"!==d.google_transport_url)f=!1;var g=!1;fe()&&(g=!0);var h=d.google_additional_params; 
h&&h.dg&&(g="e"===h.dg);h=function(k,m,q){m=void 0===m?!0:m;q=void 0===q?!0:q;Pd(a,c,d,Id(a,b,c,d,k),m,q)};d.google_gtm_experiments&&d.google_gtm_experiments.fledge&&(d.google_additional_params=d.google_additional_params||{},d.google_additional_params.fledge="1");d.google_remarketing_only?h(2):g?(le(d,f?3:2),ce(c,d),h(1),h(3),f&&h(6,!0,!1)):(le(d,f?2:1),ce(c,d),h(0),f&&h(5,!0,!1),Gd(d)&&md(c,Fd(d))&&(d.j=!0,h(0,!1)));d.google_gtm_experiments&&d.google_gtm_experiments.fledge&&ge(a,b,c,d)}d.google_remarketing_only&& 
d.google_enable_display_cookie_match&&Qd(a,c);e=!0}}catch(k){}return e} 
function ne(a,b,c,d){var e=Td(d.google_gtag_event_data.items);le(d,e.length);for(var f=0;f<e.length;f++){var g=e[f];d.google_gtm_experiments&&d.google_gtm_experiments.fledge&&(d.google_additional_params=d.google_additional_params||{},d.google_additional_params.fledge="1");Pd(a,c,d,Id(a,b,c,d,2,g),!0,!0);d.google_gtm_experiments&&d.google_gtm_experiments.fledge&&ge(a,b,c,d,g);d.google_conversion_time=d.google_conversion_time+1}};J=new function(){var a=[];var b=0,c;for(c in vb)a[b++]=vb[c];a=void 0===a?[]:a;this.m={};this.g={};for(b=0;b<a.length;++b)this.g[a[b]]=""};I(["466465925","466465926"],ib,20);wb()&&ud();J&&I(["592230570","592230571"],hb,16);xb()&&(Db(1),Eb()); 
function oe(a,b,c){function d(m,q){var p=new Image;p.onload=m;p.src=q}function e(){--f;if(0>=f){var m=Xb(a,!1),q=m[b];q&&(delete m[b],(m=q[0])&&m.call&&m())}}var f=c.length+1;if(2==c.length){var g=c[0],h=c[1];0<=Va(g,0,"rmt_tld",g.search(Wa))&&0<=Va(g,0,"ipr",g.search(Wa))&&!h.match(Ta)[6]&&(h+=Ua(g),c[1]=G(h,"rmt_tld","1"))}for(g=0;g<c.length;g++){h=c[g];var k=F(h,"fmt");switch(parseInt(k,10)){case 1:case 2:(k=a.document.getElementById("goog_conv_iframe"))&&!k.src?Ub(h,e,void 0,void 0,k,!1):d(e, 
h);break;case 4:ac(a,a.document,h,e);break;case 5:if(a.navigator&&a.navigator.sendBeacon)if(a.navigator.sendBeacon(h,"")){e();break}else h=G(h,"sendb",2);h=G(h,"fmt",3);default:d(e,h)}}e()}var pe=["GooglemKTybQhCsO"],Y=y;pe[0]in Y||"undefined"==typeof Y.execScript||Y.execScript("var "+pe[0]);for(var Z;pe.length&&(Z=pe.shift());)pe.length||void 0===oe?Y[Z]&&Y[Z]!==Object.prototype[Z]?Y=Y[Z]:Y=Y[Z]={}:Y[Z]=oe; 
window.google_trackConversion=function(a){var b=window,c=navigator,d=document;a=Sd(b,a);a.google_conversion_format=3;return me(b,c,d,a)};}).call(this);
