var game;window.onload=function(){setTimeout(function(){window.scrollTo(0,1);initGameStates()},100)};
var MainGame={title:"toiletroll",Config:{GAME_WIDTH:640,GAME_HEIGHT:960},isDebugMute:false,state:null,stateName:"",orientation:0,orientated:false,languages:["en","es","it","fr","ru","de","pt","br","tr"],language:0,styleText:{font:"42px bariol_bold",fill:"#000000",align:"center"},styleTextRU:{font:"42px shadow_regular",fill:"#000000",align:"center"},GAME_TEXT:{start:"start"},TEXT_FILE:null,weakDevice:false,onDesktop:false,old_w:false,old_h:false,pauseForAds:false,fadeColor:0,linkLogoAPI:null,linkMoreAPI:null,
linkTweetAPI:null,logoIsLoaded:false,linkAPI:null,textFPS:null,showFPS:false,isPaused:false,isGoAway:false,isMusicMuted:false,isMusicPlaying:-1,nextState:null,gameOver:false,s_musicM:null,s_sounds1:null,s_sounds2:null,s_sounds3:null,s_sounds4:null,s_sounds5:null,s_sounds6:null,s_sounds7:null,s_sounds8:null,s_sounds9:null,firstTime:true,firstGo:true,skinPaper:1,bestScore:0,lastZapusc:0,facebookNeed:false,facebookAPI:299364810422901,fromGame:false,coins:0,papers:[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0],price:[0,
350,700,1E3,1800,2500,3500,5E3,7E3,1E4,13500,16500,2E4,25E3,35E3],initSettings:function(){game.add.text(0,0,"0123456789",MainGame.styleText).destroy();game.add.text(0,0,"0123456789",MainGame.styleTextRU).destroy();game.camera.onFadeComplete.add(MainGame.changeState,this);MainGame.worldX=game.world.centerX;MainGame.worldY=game.world.centerY;MainGame.loadSaves()},continueGame:function(){game.state.start("Menu")},addText:function(vX,vY,vText,vLayer,vSize,vColor,vAnchorX,vAnchorY){if(typeof vLayer===
"undefined")vLayer="";if(typeof vSize==="undefined")vSize=40;if(typeof vColor==="undefined")vColor="#000000";if(typeof vAnchorX==="undefined")vAnchorX=0;if(typeof vAnchorY==="undefined")vAnchorY=0;var text;if(vLayer!="")text=vLayer.add(game.add.text(vX,vY,vText,MainGame.styleText));else text=game.add.text(vX,vY,vText,MainGame.styleText);text.anchor.setTo(vAnchorX,vAnchorY);text.fontSize=vSize;text.fill=vColor;return text},updateTextWidth:function(vText,vMaxWidth){var _txtWidth=vText.width;var scale=
1;if(_txtWidth>vMaxWidth){scale=vMaxWidth/_txtWidth;vText.scale.setTo(scale)}return scale},loadSaves:function(){var saved;saved=SG_Hooks.getStorageItem("bestScore");if(saved!=null)MainGame.bestScore=Number(saved);saved=SG_Hooks.getStorageItem("coins");if(saved!=null)MainGame.coins=Number(saved);saved=SG_Hooks.getStorageItem("coinTime");if(saved!=null)MainGame.lastZapusc=Number(saved);for(var j=1;j<=15;j++){saved=SG_Hooks.getStorageItem("paperOpen"+j);if(saved!=null)MainGame.papers[j-1]=Number(saved)}},
saveSaves:function(vNum,vValue){switch(vNum){case 1:SG_Hooks.setStorageItem("bestScore",MainGame.bestScore);break;case 2:SG_Hooks.setStorageItem("coins",MainGame.coins);break;case 3:SG_Hooks.setStorageItem("paperOpen"+vValue,1);break;case 4:SG_Hooks.setStorageItem("coinTime",vValue);break}},clearSaves:function(){localStorage[MainGame.title+"-c"]=null;localStorage[MainGame.title+"-b"]=null;for(var j=1;j<=15;j++)localStorage[MainGame.title+"-h"+j]=null;localStorage[MainGame.title+"-lt"]=null},clearGame:function(){game.tweens.removeAll()},
goToState:function(pNextState){MainGame.clearGame();game.camera.fade(MainGame.fadeColor,200);MainGame.nextState=pNextState},changeState:function(){game.state.start(MainGame.nextState)},fadeOut:function(){game.camera.flash(MainGame.fadeColor,200)},resizeGame:function(){var ratio=window.innerWidth/window.innerHeight;var standardWidth=640;var standardHeight=960;var maxWidth=1920;var standardRatio=standardWidth/standardHeight;if(ratio>standardRatio){game.scale.setGameSize(Math.min(maxWidth,Math.ceil(standardHeight*
ratio)),standardHeight);game.world.setBounds(Math.ceil((game.width-standardWidth)*-.5),0,game.width,game.height)}else{game.scale.setGameSize(standardWidth,standardHeight);game.world.setBounds(0,0,Math.ceil((game.height-standardHeight)*-.5),game.height)}},muteSounds:function(btn){game.add.tween(btn.scale).to({x:.9,y:.9},200,Phaser.Easing.Cubic.Out,true);game.add.tween(btn.scale).to({x:1,y:1},200,Phaser.Easing.Cubic.Out,true,260);if(game.sound.mute)btn.frameName="btn_sound_0000";else btn.frameName=
"btn_sound_0001";game.sound.mute=!game.sound.mute;MainGame.isMusicMuted=game.sound.mute},playMusic:function(num){if(MainGame.isDebugMute)return;if(MainGame.isMusicPlaying===num)return;MainGame.s_musicM.play("",0,1,true);MainGame.isMusicPlaying=num},stopMusic:function(){if(MainGame.isDebugMute)return;if(game.device.webAudio){MainGame.isMusicPlaying=-1;if(MainGame.s_musicM!=null)MainGame.s_musicM.stop()}},playSound:function(num){if(MainGame.isDebugMute)return;if(game.device.webAudio)switch(num){case 1:MainGame.s_sounds1.play();
break;case 2:MainGame.s_sounds2.play();break;case 3:MainGame.s_sounds3.play();break;case 4:MainGame.s_sounds4.play();break;case 51:MainGame.s_sounds5_1.play("",0,1,true);break;case 52:MainGame.s_sounds5_2.play();break;case 6:MainGame.s_sounds6.play();break;case 7:MainGame.s_sounds7.play();break;case 8:MainGame.s_sounds8.play();break;case 9:MainGame.s_sounds9.play();break;case 10:MainGame.s_sounds10.play();break;case 11:MainGame.s_sounds11.play();break}},showFps:function(vX,vY){if(typeof vX==="undefined")vX=
20;if(typeof vY==="undefined")vY=20;game.time.advancedTiming=true;MainGame.textFPS=game.add.text(vX,vY,"FPS",{font:"30px Arial",fill:"#FFFFFF",align:"center"});MainGame.textFPS.fixedToCamera=true},clickLogo:function(vMoreGames){if(typeof vMoreGames==="undefined")vMoreGames=true;if(MainGame.clickOne)return;try{var win=window.open("http://monkeymart.org","_blank");win.focus()}catch(err){console.log(err)}MainGame.clickOne=true;game.time.events.add(500,MainGame.clickOneBack,this)},clickOneBack:function(){MainGame.clickOne=
false}};var MyMath={getRandomInt:function(min,max){return Math.floor(Math.random()*(max-min+1))+min},getRandomBool:function(){return Math.random()<.5?true:false},shuffleArr:function(o){for(var j,x,i=o.length;i;j=Math.floor(Math.random()*i),x=o[--i],o[i]=o[j],o[j]=x);return o}};
function initGameStates(){game=new Phaser.Game(MainGame.Config.GAME_WIDTH,MainGame.Config.GAME_HEIGHT,Phaser.AUTO);game.state.add("Boot",MainGame.Boot,true);game.state.add("Preloader",MainGame.Preloader);game.state.add("Menu",MainGame.Menu);game.state.add("Game",MainGame.Game);game.state.add("Shop",MainGame.Shop);MainGame.language=SG_Hooks.getLanguage(["en"]).toLowerCase();if(MainGame.language=="ru"||MainGame.language=="en")MainGame.styleText=MainGame.styleTextRU;setTimeout(function(){window.scrollTo(0,
1)},100)}
SimpleButton=function(game,link,kuda,x,y,key,frame,callback,animationScale,vText,vSize,vColor,vDx,vDy,vLineSpacing){if(typeof vText==="undefined")vText="";if(typeof vDx==="undefined")vDx=0;if(typeof vDy==="undefined")vDy=0;if(typeof animationScale==="undefined")animationScale=0;if(typeof vSize==="undefined")vSize=42;if(typeof vColor==="undefined")vColor="#000000";if(typeof vLineSpacing==="undefined")vLineSpacing=0;_game=game;if(kuda==null)this.buttonC=game.add.group();else this.buttonC=kuda.add(game.add.group());this.buttonC.x=
x;this.buttonC.y=y;this.button=this.buttonC.add(_game.add.image(0,0,key,frame));this.button.game=_game;this.button.anchor.setTo(.5,.5);this.button.inputEnabled=true;if(MainGame.onDesktop)this.button.input.useHandCursor=true;if(vText!=""){var text=this.buttonC.add(game.add.text(0+vDx,0+vDy,vText.toUpperCase(),MainGame.styleText));text.anchor.set(.5);text.fontSize=vSize;text.fill=vColor;text.lineSpacing=vLineSpacing;this.text=text}this.button.events.onInputDown.add(function(){if(this.buttonC.alpha<
1)return;_game.add.tween(this.buttonC.scale).to({x:.9,y:.9},200,Phaser.Easing.Cubic.Out,true);_game.add.tween(this.buttonC.scale).to({x:1,y:1},200,Phaser.Easing.Cubic.Out,true,260);_game.time.events.add(250,callback,link)},this);if(animationScale>1)_game.add.tween(this.buttonC.scale).to({x:animationScale,y:animationScale},630,Phaser.Easing.Linear.None).to({x:1,y:1},630,Phaser.Easing.Linear.None).loop().start()};function trace(a){console.log(a)};
MainGame.Boot=function(game){};Phaser.Game.prototype.gamePaused=function(event){if(this._codePaused)this.sound.setMute();if(!this._paused){this._paused=true;this.time.gamePaused();this.onPause.dispatch(event)}};Phaser.Game.prototype.gameResumed=function(event){if(this._codePaused)this.sound.unsetMute();if(this._paused&&!this._codePaused){this._paused=false;this.time.gameResumed();this.input.reset();this.onResume.dispatch(event)}};
MainGame.Boot.prototype={init:function(){game.input.maxPointers=1;game.stage.backgroundColor="#BDC89F";game.scale.scaleMode=Phaser.ScaleManager.SHOW_ALL;game.scale.setResizeCallback(this.resizeGame);game.scale.pageAlignHorizontally=true;if(game.device.desktop)MainGame.onDesktop=true;else{game.scale.pageAlignVertically=true;game.scale.forceLandscape=true;if(MainGame.orientation==0)game.scale.forceOrientation(false,true);else game.scale.forceOrientation(true,false);game.scale.enterIncorrectOrientation.add(this.enterIncorrectOrientation,
this);game.scale.leaveIncorrectOrientation.add(this.leaveIncorrectOrientation,this);game.scale.onOrientationChange.add(this.changeOrientation,this)}game.load.crossOrigin="anonymous";game.onPause.add(this.onGamePause,this);game.onResume.add(this.onGameResume,this);MainGame.initSettings();SG_Hooks.setOrientationHandler(this.changeOrientation);SG_Hooks.setResizeHandler(this.resizeGame);SG_Hooks.setPauseHandler(this.onGamePause);SG_Hooks.setUnpauseHandler(this.onGameResume)},resizeGame:function(){if(MainGame.old_w!=
window.innerWidth||MainGame.old_h!=window.innerHeight){MainGame.old_w=window.innerWidth;MainGame.old_h=window.innerHeight;MainGame.resizeGame()}},preload:function(){game.load.image("preloaderBackground","assets/preloader_back.png?r=2");game.load.image("preloaderBar","assets/preloader_bar.png?r=2");game.load.image("bg","assets/entities/bg.png?r=3");game.load.image("logo","assets/logo.png?r=0")},create:function(){game.state.start("Preloader")},onGamePause:function(){if(!game.sound.mute){MainGame.isGoAway=
true;game.sound.mute=true}else MainGame.isGoAway=false},onGameResume:function(){if(MainGame.isGoAway)game.sound.mute=false},enterIncorrectOrientation:function(){setTimeout(function(){window.scrollTo(0,1)},100);MainGame.orientated=false;document.getElementById("orientation").style.display="block";if(!game.device.android){document.getElementById("orientation").style.width=window.innerWidth*1.05+"px";document.getElementById("orientation").style.height=window.innerHeight*1.05+"px"}},leaveIncorrectOrientation:function(){MainGame.orientated=
true;document.getElementById("orientation").style.display="none"},changeOrientation:function(){}};
MainGame.Menu=function(game){this.layerMain=null};
MainGame.Menu.prototype={create:function(){MainGame.state=this;MainGame.stateName="Menu";MainGame.GAME_TEXT=MainGame.TEXT_FILE[MainGame.language];var bg=game.add.image(MainGame.worldX,0,"bg");bg.anchor.setTo(.5,0);this.layerMain=game.add.group();this.layerBack=this.layerMain.add(game.add.group());var pn_foot=this.layerMain.add(game.add.image(320,670,"ss_main","panel_3_0000"));pn_foot.anchor.setTo(.5,0);this.btnStartGame=new SimpleButton(game,this,this.layerMain,320,770,"ss_main","btn_play_0000",this.startGame,
1.05,MainGame.GAME_TEXT.play,88,"#383647",2,5);this.btnStartGame.buttonC.angle=-2;if(SG_Hooks.isEnabledIncentiviseButton())this.initCoinGift();this.btnShop=new SimpleButton(game,this,this.layerMain,320+130,888,"ss_main","btn_shop_0000",this.goToShop,1,MainGame.GAME_TEXT.shop,60,"#8A879B",0,5);this.btnMoreGames=new SimpleButton(game,this,this.layerMain,320-130,888,"ss_main","btn_moregames_0000",MainGame.clickLogo,1,MainGame.GAME_TEXT.more_games,40,"#8A879B",0,5);this.btnMoreGames.buttonC.angle=2;this.btnMoreGames.text.lineSpacing=
-10;this.musicButton=this.layerMain.add(game.add.image(577,65,"ss_main","btn_sound_0000"));this.musicButton.anchor.setTo(.5,.5);this.musicButton.angle=10;this.musicButton.inputEnabled=true;this.musicButton.events.onInputDown.add(MainGame.muteSounds,this);if(MainGame.isMusicMuted)this.musicButton.frameName="btn_sound_0001";MainGame.playMusic(0);if(MainGame.bestScore>0){var plaha=this.layerMain.add(game.add.image(320,290,"ss_main","panel_bestscore_0000"));plaha.anchor.setTo(.5);var bestScoreText=MainGame.addText(320,
296,MainGame.GAME_TEXT.your_best_score+": "+MainGame.bestScore+" "+MainGame.GAME_TEXT.points,this.layerMain,34,"#ffffff",.5,.5);MainGame.updateTextWidth(bestScoreText,620)}var title=this.layerMain.add(game.add.image(320+5,106,"ss_main","logo_0000"));title.anchor.setTo(.5,0);this.countMaxPaper=100;this.addHolderPaper();this.initPaperRoll();SG_Hooks.start();SG_Hooks.pageDisplayed(SG_Hooks.PAGE_MAIN_MENU);SG_Hooks.triggerIncentivise(this.callBackAds);MainGame.updateTextWidth(this.btnStartGame.text,220);
MainGame.updateTextWidth(this.btnShop.text,190);MainGame.updateTextWidth(this.btnMoreGames.text,190)},callBackAds:function(result){if(result==true)console.log("ads")},playOnce:function(){if(!MainGame.firstGo)return;MainGame.firstGo=false;this.musicButton.frameName="btn_sound_0000";MainGame.playMusic(0)},startGame:function(){game.state.start("Game")},goToShop:function(){MainGame.fromGame=false;MainGame.goToState("Shop")},initCoinGift:function(){var isCollectCoin=false;var textTime="";var skok=180;
if(MainGame.lastZapusc==0){MainGame.saveSaves(4,this.getNext3hour());MainGame.lastZapusc=this.getNext3hour()}else{var now=new Date;skok=this.getDiffInMinutes(MainGame.lastZapusc,now.getTime());if(skok<=0)isCollectCoin=true}if(isCollectCoin){this.btnCoins=new SimpleButton(game,this,this.layerMain,150,58,"ss_main","btn_timec_0000",this.collectCoins,1,MainGame.GAME_TEXT.collect_coins,32,"#F7ED28",30,6,-8);MainGame.updateTextWidth(this.btnCoins.text,110)}else{var plaha=this.layerMain.add(game.add.image(150,
58,"ss_main","btn_timec_0000"));plaha.anchor.setTo(.5);if(skok>60)textTime=Math.floor(skok/60)+MainGame.GAME_TEXT.short_hour+" "+skok%60+MainGame.GAME_TEXT.short_minute;else textTime=skok+MainGame.GAME_TEXT.short_minute;var textFree=MainGame.addText(180,48,MainGame.GAME_TEXT.free_500,this.layerMain,30,"#F7ED28",.5,.5);var txtTime=MainGame.addText(185,80,textTime,this.layerMain,30,"#F7ED28",.5,.5);MainGame.updateTextWidth(textFree,160);MainGame.updateTextWidth(txtTime,115)}},collectCoins:function(){MainGame.playSound(9);
MainGame.coins+=500;MainGame.saveSaves(2);MainGame.lastZapusc=0;game.state.start("Menu")},getNext3hour:function(){var now=new Date;var after3hours=new Date(now.getFullYear(),now.getMonth(),now.getDate(),now.getHours(),now.getMinutes()+180);return after3hours.getTime()},getDiffInMinutes:function(vPar1,vPar2){var diff=vPar1-vPar2;var seconds=Math.floor(diff/1E3);var minutes=Math.floor(seconds/60);return minutes},showCredits:function(){MainGame.goToState("Credits")},addHolderPaper:function(){for(var i=
0;i<15;i++)if(MainGame.papers[i]==1)MainGame.skinPaper=i+1;this.paperH=300;this.paperW=200;var skinPaper="paper"+MainGame.skinPaper;this.hui=this.layerBack.add(game.add.image(380,320,"ss_main","holder2_0000"));this.rulon=this.layerBack.add(game.add.image(180,395,"ss_main","button_0000"));this.paper_tile2=this.layerBack.add(game.add.tileSprite(0,0,60,114,skinPaper));this.greyBlok=this.layerBack.add(game.add.graphics(0,0));this.greyBlok.alpha=.6;this.paper_tile1=this.layerBack.add(game.add.tileSprite(0,
0,250,this.paperH*2+50,skinPaper));this.circle1=this.layerBack.add(game.add.graphics(0,0));this.hole=this.layerBack.add(game.add.image(0,0,"ss_main","hole_0000"));this.hole.anchor.setTo(.5,.5);this.layerBack.add(game.add.image(17,320,"ss_main","holder_0000"));this.mask=this.layerBack.add(game.add.graphics(0,0));this.paper_tile1.mask=this.mask},initPaperRoll:function(){this.offsetPaperX=20;this.savedPositionY=0;this.isCanRoll=true;this.paper_tile1.tilePosition.y=0;this.paper_tile1.tilePosition.x=this.offsetPaperX;
this.movingSpeed=0;this.deltaS=0;this.isCanTear=true;this.isPaperTear=false;this.tripDistance=0;this.paperDistance=0;this.countPaper=0;this.lastCountPaper=0;this.arrayPPS=[];this.isPaperAdded=true;this.isPotyanuto=false;this.paper_tile2.visible=true;this.circle1.visible=true;this.greyBlok.visible=true;this.updateEllipseSize();this.updateMask(200)},updateEllipseSize:function(){var count=this.countMaxPaper-this.countPaper;var p=count/this.countMaxPaper;var maxEllipsW=57-25;var maxEllipsH=114-50;this.ellipsW=
25+maxEllipsW*p;this.ellipsH=50+maxEllipsH*p;this.posBx=222;this.posBy=462;this.posAx=this.posBx;this.posAy=this.posBy-this.ellipsH;this.posCxf=this.posBx+57;this.posCx=this.posBx+this.ellipsW;this.posCy=this.posBy;this.paper_tile2.height=this.ellipsH;this.paper_tile2.x=this.posBx;this.paper_tile2.y=this.posBy;this.greyBlok.clear();this.greyBlok.beginFill(3355443);this.greyBlok.drawRect(this.posBx,this.posBy,60,this.ellipsH);this.greyBlok.endFill();this.paper_tile1.x=this.posAx;this.paper_tile1.y=
348;this.hole.x=222;this.hole.y=this.posBy;this.circle1.clear();this.circle1.beginFill(13421772);this.circle1.drawEllipse(this.posBx,this.posBy,this.ellipsW,this.ellipsH);this.circle1.endFill();var delta=Math.floor(this.posCxf-this.posCx);this.paper_tile1.x=this.posAx-delta},updateMask:function(vPosY){this.mask.clear();this.mask.beginFill(16777215);this.mask.drawEllipse(this.posBx+this.paperW,this.posBy,this.ellipsW,this.ellipsH);this.mask.drawRect(this.posAx,this.posAy,this.paperW,this.ellipsH);
this.mask.drawRect(this.posCx,this.posCy,this.paperW,vPosY);this.mask.endFill()}};
MainGame.Preloader=function(game){this.background=null;this.preloadBar=null;this.ready=false};
MainGame.Preloader.prototype={preload:function(){var bg=game.add.image(MainGame.worldX,0,"bg");bg.anchor.setTo(.5,0);var logo=game.add.image(MainGame.worldX,MainGame.worldY-100,"logo");logo.anchor.setTo(.5);logo.inputEnabled=true;logo.events.onInputUp.add(MainGame.clickLogo);var width=Math.ceil(397/2);this.background=game.add.image(MainGame.worldX-width,MainGame.worldY+40,"preloaderBackground");this.preloadBar=game.add.image(MainGame.worldX-width,MainGame.worldY+40,"preloaderBar");game.load.setPreloadSprite(this.preloadBar);
game.load.atlasJSONHash("ss_main","assets/spritesheets/ss_main.png?r=18","assets/spritesheets/ss_main.json?r=18");for(var i=1;i<=15;i++)game.load.image("paper"+i,"assets/entities/paper"+i+".png");game.load.audio("music",["assets/audio/ogg/ingame.ogg","assets/audio/mp3/ingame.mp3"]);if(this.game.device.webAudio){game.load.audio("sfx02good",["assets/audio/ogg/sfx02good.ogg?r=3","assets/audio/mp3/sfx02good.mp3?r=3"]);game.load.audio("sfx03perfect",["assets/audio/ogg/sfx03perfect.ogg","assets/audio/mp3/sfx03perfect.mp3"]);
game.load.audio("sfx04empty",["assets/audio/ogg/sfx04empty.ogg","assets/audio/mp3/sfx04empty.mp3"]);game.load.audio("sfx05loopfire",["assets/audio/ogg/sfx05loopfire.ogg","assets/audio/mp3/sfx05loopfire.mp3"]);game.load.audio("sfx05onfire",["assets/audio/ogg/sfx05onfire.ogg","assets/audio/mp3/sfx05onfire.mp3"]);game.load.audio("sfx06tear",["assets/audio/ogg/sfx06tear.ogg","assets/audio/mp3/sfx06tear.mp3"]);game.load.audio("sfx07tick",["assets/audio/ogg/sfx07tick.ogg","assets/audio/mp3/sfx07tick.mp3"]);
game.load.audio("sfx08endoflevel",["assets/audio/ogg/sfx08endoflevel.ogg","assets/audio/mp3/sfx08endoflevel.mp3"]);game.load.audio("sfx09coin",["assets/audio/ogg/sfx09coin.ogg","assets/audio/mp3/sfx09coin.mp3"]);game.load.audio("sfx10coming",["assets/audio/ogg/sfx10coming.ogg","assets/audio/mp3/sfx10coming.mp3"]);game.load.audio("sfx11out",["assets/audio/ogg/sfx11out.ogg","assets/audio/mp3/sfx11out.mp3"])}game.load.json("alltext","assets/text/text.json")},create:function(){MainGame.s_musicM=game.add.audio("music",
1,true);if(game.device.webAudio){MainGame.s_sounds2=game.add.audio("sfx02good",.6);MainGame.s_sounds3=game.add.audio("sfx03perfect",.2);MainGame.s_sounds4=game.add.audio("sfx04empty",.45);MainGame.s_sounds5_1=game.add.audio("sfx05loopfire",1);MainGame.s_sounds5_2=game.add.audio("sfx05onfire",.6);MainGame.s_sounds6=game.add.audio("sfx06tear",1.1);MainGame.s_sounds7=game.add.audio("sfx07tick",1.15);MainGame.s_sounds8=game.add.audio("sfx08endoflevel",1);MainGame.s_sounds9=game.add.audio("sfx09coin",
1.2);MainGame.s_sounds10=game.add.audio("sfx10coming",.9);MainGame.s_sounds11=game.add.audio("sfx11out",.9)}MainGame.TEXT_FILE=game.cache.getJSON("alltext")},update:function(){if(this.ready==false){this.ready=true;MainGame.continueGame()}}};
MainGame.Shop=function(game){this.layerMain=null};
MainGame.Shop.prototype={create:function(){MainGame.state=this;MainGame.stateName="Shop";var bg=game.add.image(MainGame.worldX,0,"bg");bg.anchor.setTo(.5,0);this.layerMain=game.add.group();this.layerBack=this.layerMain.add(game.add.group());var pn_foot=this.layerMain.add(game.add.image(320,-50,"ss_main","panel_2_0000"));pn_foot.anchor.setTo(.5,0);this.layerMain.add(game.add.image(200,10,"ss_main","coins_0000"));this.textCoin=MainGame.addText(308,60,MainGame.coins,this.layerMain,60,"#383647",0,.5);
this.btnMenu=new SimpleButton(game,this,this.layerMain,70,55,"ss_main","btn_back_0000",this.goToMenu);this.updatePaper();this.initScroll(-750,0);MainGame.fadeOut();SG_Hooks.pageDisplayed(SG_Hooks.PAGE_SHOP)},updatePaper:function(){this.layerBack.removeAll();this.textCoin.setText(MainGame.coins);var obj;var start_pX=110;var start_pY=160;var pX=0;var pY=0;var numPaper=1;for(var i=0;i<5;i++)for(var j=0;j<3;j++){pX=start_pX+210*j;pY=start_pY+310*i;obj=this.layerBack.add(game.add.image(pX,pY,"ss_main",
"panel_shop_0000"));obj.anchor.setTo(.5,0);obj=this.layerBack.add(game.add.image(pX+10,pY+15,"ss_main","a_roll"+numPaper+"_0000"));obj.anchor.setTo(.5,0);if(MainGame.papers[numPaper-1]==1){obj=this.layerBack.add(game.add.image(pX,pY+230,"ss_main","btn_selected_0000"));obj.anchor.setTo(.5)}else{var btnBuy=this.layerBack.add(game.add.image(pX,pY+245,"ss_main","btn_buy_0000"));btnBuy.anchor.setTo(.5);btnBuy.angle=-2;var txt=MainGame.addText(pX+4,pY+249,MainGame.GAME_TEXT.buy,this.layerBack,48,"#5BC423",
.5,.5);txt.angle=-2;MainGame.updateTextWidth(txt,120);if(MainGame.coins<MainGame.price[numPaper-1]){btnBuy.alpha=.5;txt.alpha=.5}else{btnBuy.inputEnabled=true;btnBuy.id=numPaper-1;btnBuy.events.onInputUp.add(this.buyPaper,this)}obj=this.layerBack.add(game.add.image(pX-45,pY+190,"ss_main","money_0000"));obj.anchor.setTo(.5);MainGame.addText(pX-20,pY+192,MainGame.price[numPaper-1],this.layerBack,36,"#383647",0,.5)}numPaper++}},buyPaper:function(vElem){var dist=Math.abs(this.delta);if(dist>10)return;
var num=vElem.id;MainGame.coins-=MainGame.price[num];MainGame.papers[num]=1;MainGame.saveSaves(3,num+1);MainGame.saveSaves(2);this.updatePaper();MainGame.playSound(9)},initScroll:function(vMin,vMax){this.isBeingDragged=false;this.game.input.onDown.add(this.beginMove,this);this.game.input.onUp.add(this.endMove,this);this.scrollMin=vMin;this.scrollMax=vMax},beginMove:function(pointer,x,y){this.startY=this.game.input.y;this.isBeingDragged=true;this.savedPositionY=this.layerBack.y},endMove:function(pointer,
x,y){this.isBeingDragged=false;this.savedPositionY=this.layerBack.y},update:function(){if(this.isBeingDragged){this.delta=this.startY-this.game.input.y;this.layerBack.y=this.savedPositionY-this.delta;if(this.layerBack.y<=this.scrollMin)this.layerBack.y=this.scrollMin;if(this.layerBack.y>=this.scrollMax)this.layerBack.y=this.scrollMax}},goToMenu:function(){if(MainGame.fromGame)MainGame.goToState("Game");else MainGame.goToState("Menu")}};
MainGame.Game=function(game){this.layerMain=null};
MainGame.Game.prototype={create:function(){MainGame.state=this;MainGame.stateName="Game";var bg=game.add.image(MainGame.worldX,0,"bg");bg.anchor.setTo(.5,0);this.layerMain=game.add.group();this.layerBack=this.layerMain.add(game.add.group());this.layerPanel=this.layerMain.add(game.add.group());this.layerFinish=this.layerMain.add(game.add.group());this.layerPauseBack=this.layerMain.add(game.add.group());this.layerPauseBack.x=320;this.layerPause=this.layerMain.add(game.add.group());this.countMaxPaper=
100;this.speedMult=.8;this.friction=.98;this.speedMax=125;this.speedGood=this.speedMax*.5;this.timerGame=40;this.scoreGame=0;this.countPaperGame=0;this.numPaper=-1;this.gameOver=false;this.testScore=0;this.timerBool=true;this.countX2=3;this.addHolderPaper();this.initPaperRoll();MainGame.isPaused=false;var pn_foot=this.layerPanel.add(game.add.image(320,0,"ss_main","panel_2_0000"));pn_foot.anchor.setTo(.5,0);this.textPaperPerSec=MainGame.addText(270-20,133+10,0,this.layerPanel,60,"#8C899D",1,.5);var txtPerSec=
MainGame.addText(280-20,135+10,MainGame.GAME_TEXT.per_second,this.layerPanel,32,"#8C899D",0,.5);MainGame.updateTextWidth(txtPerSec,210);this.timerIcon=this.layerPanel.add(game.add.image(60+200,65,"ss_main","timer_0000"));this.timerIcon.anchor.setTo(.5,.5);this.timerIcon.angle=-7;this.textTimer=MainGame.addText(108+200,70,this.timerGame,this.layerPanel,80,"#3AABF5",0,.5);var txtScoreT=MainGame.addText(550,40,MainGame.GAME_TEXT.score+":",this.layerPanel,42,"#8C899D",.5,.5);MainGame.updateTextWidth(txtScoreT,
210);this.txtScore=MainGame.addText(550,90,this.scoreGame,this.layerPanel,70,"#393748",.5,.5);txtScoreT.angle=4;this.initScroll(this.paper_tile1.tilePosition,this.paper_tile2.tilePosition);this.timerLevel=game.time.create(false);this.timerLevel.loop(1E3,this.updateTimer,this);game.time.events.loop(500,this.updatePPS,this);this.informer=MainGame.addText(320,265," "+MainGame.GAME_TEXT.pull_paper_down.toUpperCase()+"! ",this.layerPanel,55,"#F1F4FF",.5,.5);this.informer.lineSpacing=-10;this.informer.fontSize=
62;this.informer.setShadow(0,0,"rgba(0,0,0,1)",16);this.isShowTutorial=true;this.mxPower=this.layerPanel.add(game.add.image(320,330,"ss_main","t_x2_0000"));this.mxPower.anchor.setTo(.5,.5);this.mxPower.visible=false;MainGame.playMusic(0);this.pauseButton=this.layerMain.add(game.add.image(65,65,"ss_main","btn_pause_0000"));this.pauseButton.anchor.setTo(.5,.5);var spr_bg=this.layerPauseBack.add(this.game.add.graphics(-(this.game.width/2),0));spr_bg.beginFill(1713987,.65);spr_bg.drawRect(0,0,this.game.width,
this.game.height);spr_bg.endFill();this.layerPauseBack.visible=false;this.layerPause.visible=false;var poxPauseY=200;var txtPaused=MainGame.addText(320,poxPauseY+100,MainGame.GAME_TEXT.paused.toUpperCase(),this.layerPause,80,"#ffffff",.5,.5);this.btnPauseContinue=this.layerPause.add(game.add.image(320,poxPauseY+200,"ss_main","btn_continue_0000"));this.btnPauseContinue.anchor.setTo(.5,.5);var txtCont=MainGame.addText(320,poxPauseY+200,MainGame.GAME_TEXT.txt_continue.toUpperCase(),this.layerPause,44,
"#ffffff",.5,.4);this.btnPauseMore=this.layerPause.add(game.add.image(320,poxPauseY+300+20,"ss_main","btn_moregames_0000"));this.btnPauseMore.anchor.setTo(.5,.5);var txtMpre=MainGame.addText(320,poxPauseY+300+18,MainGame.GAME_TEXT.more_games.toUpperCase(),this.layerPause,40,"#ffffff",.5,.4).lineSpacing=-10;this.btnPauseHome=this.layerPause.add(game.add.image(320-80,poxPauseY+400+40,"ss_main","btn_home_0000"));this.btnPauseHome.anchor.setTo(.5,.5);this.musicPauseButton=this.layerPause.add(game.add.image(320+
80,poxPauseY+400+40,"ss_main","btn_sound_0000"));this.musicPauseButton.anchor.setTo(.5,.5);this.musicPauseButton.angle=10;MainGame.updateTextWidth(txtPaused,270);MainGame.updateTextWidth(txtCont,210);MainGame.updateTextWidth(txtMpre,180);SG_Hooks.levelStarted(1);game.input.onUp.add(this.clickStageUp,this)},isClickedPause:function(){if(this.gameOver)return false;var clickPosX=this.game.input.worldX;var clickPosY=this.game.input.worldY;var _isPause=clickPosX>this.pauseButton.x-50&&clickPosX<this.pauseButton.x+
50&&clickPosY>this.pauseButton.y-50&&clickPosY<this.pauseButton.y+50;if(_isPause)this.pauseGame();return _isPause},pauseGame:function(){MainGame.isPaused=!MainGame.isPaused;game.paused=MainGame.isPaused;if(MainGame.isMusicMuted)game.sound.setMute();else game.sound.unsetMute();if(game.sound.mute)this.musicPauseButton.frameName="btn_sound_0001";else this.musicPauseButton.frameName="btn_sound_0000";this.layerPauseBack.visible=MainGame.isPaused;this.layerPause.visible=MainGame.isPaused},clickStageUp:function(){if(!MainGame.isPaused)return;
var clickPosX=this.game.input.worldX;var clickPosY=this.game.input.worldY;if(clickPosX>this.btnPauseContinue.x-130&&clickPosX<this.btnPauseContinue.x+130&&clickPosY>this.btnPauseContinue.y-45&&clickPosY<this.btnPauseContinue.y+45)this.pauseGame();else if(clickPosX>this.btnPauseHome.x-90&&clickPosX<this.btnPauseHome.x+90&&clickPosY>this.btnPauseHome.y-65&&clickPosY<this.btnPauseHome.y+65){game.paused=false;if(MainGame.isMusicMuted)game.sound.setMute();else game.sound.unsetMute();this.state.start("Menu")}else if(clickPosX>
this.btnPauseMore.x-120&&clickPosX<this.btnPauseMore.x+120&&clickPosY>this.btnPauseMore.y-45&&clickPosY<this.btnPauseMore.y+45)MainGame.clickLogo();else if(clickPosX>this.musicPauseButton.x-65&&clickPosX<this.musicPauseButton.x+65&&clickPosY>this.musicPauseButton.y-65&&clickPosY<this.musicPauseButton.y+65)MainGame.muteSounds(this.musicPauseButton)},showInfo:function(vNum){if(vNum>1)this.mxPower.alpha=0;if(vNum==0)MainGame.playSound(3);if(vNum==1)MainGame.playSound(2);if(vNum==3)MainGame.playSound(6);
if(vNum==5)MainGame.playSound(4);if(vNum==6)if(game.device.webAudio){if(!MainGame.s_sounds5_1.isPlaying)MainGame.playSound(51);if(!MainGame.s_sounds5_2.isPlaying)MainGame.playSound(52)}var arStr=["t_perfect","t_great","t_tutorial","t_nottoofast","t_specialsample","t_empty","t_youareonfire"];var arText=[MainGame.GAME_TEXT.perfect,MainGame.GAME_TEXT.great,MainGame.GAME_TEXT.pull_paper_down,MainGame.GAME_TEXT.not_too_fast,MainGame.GAME_TEXT.special_sample,MainGame.GAME_TEXT.empty,MainGame.GAME_TEXT.you_are_on_fire];
var arColor=["#75FF2C","#3FAFFF","#F1F4FF","#FF3710","#FF3FA6","#4DE2FF","#FF831C"];this.informer.setText(" "+arText[vNum].toUpperCase()+"! ");this.informer.fill=arColor[vNum];this.informer.visible=true;this.informer.alpha=0;this.informer.y=290;game.tweens.removeFrom(this.informer);game.add.tween(this.informer).to({alpha:1},400,Phaser.Easing.Linear.None,true);game.add.tween(this.informer).to({y:260},1E3,Phaser.Easing.Elastic.Out,true).onComplete.add(this.twInformerCompleted,this)},showPerfectM:function(vNum){if(vNum<
1||vNum>4)return;var nn=this.countPerfect+1;this.mxPower.frameName="t_x"+nn+"_0000";this.mxPower.visible=true;this.mxPower.alpha=0;this.mxPower.y=360;this.mxPower.scale.setTo(1);game.tweens.removeFrom(this.mxPower);game.add.tween(this.mxPower).to({alpha:1},400,Phaser.Easing.Linear.None,true);game.add.tween(this.mxPower.scale).to({x:1.15,y:1.15},150,Phaser.Easing.Linear.None,true,0,4,true);game.add.tween(this.mxPower).to({y:330},1E3,Phaser.Easing.Elastic.Out,true).onComplete.add(this.twInformerMCompleted,
this)},twInformerCompleted:function(){game.add.tween(game.state.states.Game.informer).to({alpha:0},300,Phaser.Easing.Linear.None,true,600).onComplete.add(function(){game.state.states.Game.informer.visible=false})},twInformerMCompleted:function(){game.add.tween(game.state.states.Game.mxPower).to({alpha:0},300,Phaser.Easing.Linear.None,true,600).onComplete.add(function(){game.state.states.Game.mxPower.visible=false})},checkFire:function(){if(game.device.webAudio)MainGame.s_sounds5_1.stop();if(this.isFireEffect){game.add.tween(this.groupFire).to({alpha:0},
300,Phaser.Easing.Linear.None,true).onComplete.add(function(){game.state.states.Game.groupFire.removeAll()});this.isFireEffect=false}},addFireEffect:function(){this.groupFire.removeAll();this.groupFire.alpha=1;this.addFire(437,510-140);this.addFire(330,445-140);this.addFire(232,510-140);this.isFireEffect=true;game.time.events.add(2E3,this.checkFire,this).autoDestroy=true},addFire:function(vX,vY){var koster=this.groupFire.add(game.add.sprite(vX,vY,"ss_main"));koster.anchor.setTo(.5,.5);koster.animations.add("fire",
Phaser.Animation.generateFrameNames("fire_",0,15,"",4),30);koster.animations.play("fire",30,true)},addHolderPaper:function(){for(var i=0;i<15;i++)if(MainGame.papers[i]==1)MainGame.skinPaper=i+1;this.paperH=300;this.paperW=200;var skinPaper="paper"+MainGame.skinPaper;this.layerBack.add(game.add.image(380,320,"ss_main","holder2_0000"));this.groupFire=this.layerBack.add(game.add.group());this.rulon=this.layerBack.add(game.add.image(180,395,"ss_main","button_0000"));this.rulon.scale.x=.95;this.paper_tile2=
this.layerBack.add(game.add.tileSprite(0,0,60,114,skinPaper));this.greyBlok=this.layerBack.add(game.add.graphics(0,0));this.greyBlok.alpha=.6;this.paper_tile1=this.layerBack.add(game.add.tileSprite(0,0,250,this.paperH*2+50,skinPaper));this.circle1=this.layerBack.add(game.add.graphics(0,0));this.hole=this.layerBack.add(game.add.image(0,0,"ss_main","hole_0000"));this.hole.anchor.setTo(.5,.5);this.layerBack.add(game.add.image(17,320,"ss_main","holder_0000"));this.mask=this.layerBack.add(game.add.graphics(0,
0));this.paper_tile1.mask=this.mask},updateTimer:function(){if(this.gameOver)return;this.timerGame--;this.textTimer.setText(this.timerGame);if(this.timerGame>=1&&this.timerGame<=5){MainGame.playSound(7);game.add.tween(this.timerIcon.scale).to({x:1.1,y:1.1},200,Phaser.Easing.Linear.None,true,0,0,true)}if(this.timerGame==0)this.showFinishScreen()},showFinishScreen:function(){MainGame.stopMusic();MainGame.playSound(8);this.gameOver=true;this.pauseButton.visible=false;game.input.onUp.remove(this.clickStageUp,
this);this.levelCoins=Math.floor(this.scoreGame/5);this.layerPanel.visible=false;var title=this.layerFinish.add(game.add.image(300,125,"ss_main","panel_1_0000"));title.anchor.setTo(.5,0);var txtTimeUp=MainGame.addText(320,193,MainGame.GAME_TEXT.times_up,this.layerFinish,68,"#383647",.5,.5);MainGame.updateTextWidth(txtTimeUp,350);var obj=this.layerFinish.add(game.add.image(320,295,"ss_main","cup_0000"));obj.anchor.setTo(.5);obj.angle=-3;MainGame.addText(320-130,270,this.scoreGame,this.layerFinish,
66,"#383647",.5,.5);MainGame.addText(320+130,270,MainGame.bestScore,this.layerFinish,66,"#383647",.5,.5);var txtCurr=MainGame.addText(320-130,320,MainGame.GAME_TEXT.current,this.layerFinish,32,"#8A879B",.5,.5);var txtBest=MainGame.addText(320+130,320,MainGame.GAME_TEXT.best,this.layerFinish,32,"#8A879B",.5,.5);MainGame.updateTextWidth(txtCurr,190);MainGame.updateTextWidth(txtBest,190);this.layerFinish.add(game.add.image(10,10,"ss_main","coins_0000"));this.textCoin=MainGame.addText(10+108,60,MainGame.coins,
this.layerFinish,60,"#383647",0,.5);this.musicButton=this.layerFinish.add(game.add.image(577,65,"ss_main","btn_sound_0000"));this.musicButton.anchor.setTo(.5,.5);this.musicButton.angle=10;this.musicButton.inputEnabled=true;this.musicButton.events.onInputDown.add(MainGame.muteSounds,this);if(MainGame.isMusicMuted)this.musicButton.frameName="btn_sound_0001";this.layerFinish.y=-800;game.add.tween(this.layerFinish).to({y:0},1100,Phaser.Easing.Elastic.Out,true);var isBeating=false;var firstTimeHigh=false;
if(MainGame.bestScore<this.scoreGame){if(MainGame.bestScore==0)firstTimeHigh=true;MainGame.bestScore=this.scoreGame;isBeating=true}if(isBeating&&!firstTimeHigh){var txtSuper=MainGame.addText(320,395,MainGame.GAME_TEXT["super"]+"!",this.layerFinish,56,"#FF3327",.5,.5);var scSuper=MainGame.updateTextWidth(txtSuper,220);game.add.tween(txtSuper.scale).to({x:scSuper+.15,y:scSuper+.15},150,Phaser.Easing.Linear.None,true,0,3,true);var txtBeat=MainGame.addText(320,455,MainGame.GAME_TEXT.you_beat,this.layerFinish,
30,"#8A879B",.5,.5);MainGame.updateTextWidth(txtBeat,400);var obj=this.layerFinish.add(game.add.image(245,530,"ss_main","moneyB_0000"));obj.anchor.setTo(.5);MainGame.addText(295,530,"+25",this.layerFinish,90,"#383647",0,.5);this.btnContinue=new SimpleButton(game,this,this.layerFinish,320,705,"ss_main","btn_continue_0000",this.tryAgain,1,MainGame.GAME_TEXT.txt_continue.toUpperCase(),34,"#393748",0,5);this.btnShare=new SimpleButton(game,this,this.layerFinish,320,610,"ss_main","btn_share_0000",this.shareFacebook,
1,MainGame.GAME_TEXT.share,34,"#383647",28,5);MainGame.updateTextWidth(this.btnContinue.text,200);MainGame.updateTextWidth(this.btnShare.text,120);if(this.levelCoins>0)game.time.events.add(1100,this.startCoinEffect,this,-30,70).autoDestroy=true}else{var txtCoins=MainGame.addText(320,385,MainGame.GAME_TEXT.your_coins+":",this.layerFinish,42,"#8A879B",.5,.5);MainGame.updateTextWidth(txtCoins,300);if(SG_Hooks.isEnabledIncentiviseButton()){this.btnCoinX2=new SimpleButton(game,this,this.layerFinish,412,
455,"ss_main","btn_tv_0000",this.showTvAds);this.btnCoinX2.buttonC.angle=-3;this.txtLevelCoins=MainGame.addText(310,464,this.levelCoins,this.layerFinish,50,"#383647",1,.5);this.iconCoin=this.layerFinish.add(game.add.image(310-this.txtLevelCoins.width,460,"ss_main","moneyB_0000"));this.iconCoin.anchor.setTo(1,.5);if(this.levelCoins>0)game.time.events.add(1100,this.startCoinEffect,this,-this.txtLevelCoins.width).autoDestroy=true}else{this.txtLevelCoins=MainGame.addText(310+65,464,this.levelCoins,this.layerFinish,
50,"#383647",1,.5);this.iconCoin=this.layerFinish.add(game.add.image(310-this.txtLevelCoins.width+65,460,"ss_main","moneyB_0000"));this.iconCoin.anchor.setTo(1,.5);if(this.levelCoins>0)game.time.events.add(1100,this.startCoinEffect,this,-this.txtLevelCoins.width+65).autoDestroy=true}this.btnTryAgain=new SimpleButton(game,this,this.layerFinish,320,576,"ss_main","btn_tryagain_0000",this.tryAgain,1.05,MainGame.GAME_TEXT.try_again,46,"#383647",0,5);this.btnTryAgain.buttonC.angle=1.5;this.btnMenu=new SimpleButton(game,
this,this.layerFinish,320,685,"ss_main","btn_shop_0000",this.goToMenu,1,MainGame.GAME_TEXT.shop,60,"#8A879B",0,5);MainGame.updateTextWidth(this.btnTryAgain.text,220);MainGame.updateTextWidth(this.btnMenu.text,190)}MainGame.saveSaves(1,MainGame.bestScore);SG_Hooks.levelFinished(1,this.scoreGame);SG_Hooks.gameOver(1,this.scoreGame);SG_Hooks.pageDisplayed(SG_Hooks.PAGE_GAME_OVRE);SG_Hooks.triggerIncentivise(this.callBackAds)},startCoinEffect:function(vX,vY,vShare){if(typeof vX==="undefined")vX=0;if(typeof vY===
"undefined")vY=0;if(typeof vShare==="undefined")vShare=false;this.addCoinTween(vX,vY,100);this.addCoinTween(vX,vY,150);this.addCoinTween(vX,vY,200);if(vShare)game.time.events.add(1E3,this.addCoinsFromShare,this).autoDestroy=true;else game.time.events.add(1E3,this.addCoinsFromLevel,this).autoDestroy=true},addCoinsFromLevel:function(){MainGame.coins+=this.levelCoins;MainGame.state.textCoin.setText(MainGame.coins);MainGame.saveSaves(2,MainGame.coins);MainGame.playSound(9)},addCoinsFromShare:function(){MainGame.coins+=
25;MainGame.state.textCoin.setText(MainGame.coins);MainGame.saveSaves(2,MainGame.coins);MainGame.playSound(9)},addCoinTween:function(vX,vY,vDelay){var _posX=265+vX+MyMath.getRandomInt(-10,10);var _posY=460+vY+MyMath.getRandomInt(-10,10);var obj=this.layerFinish.add(game.add.image(_posX,_posY,"ss_main","moneyB_0000"));obj.anchor.setTo(.5);game.add.tween(obj).to({x:55,y:55},800,"Back.easeIn",true,vDelay).onComplete.add(function(){obj.destroy()})},shareFacebook:function(){MainGame.state.startCoinEffect(-30,
70,true);MainGame.state.btnShare.buttonC.alpha=.6;try{var link="https://www.facebook.com/sharer/sharer.php?u="+window.location.href+"&description="+"Yay I got "+String(MainGame.bestScore)+"! Can you beat me?";var win=window.open(link,"_blank");win.focus()}catch(err){console.log(err)}},updatePPS:function(){var speed=Math.round(this.countPaper-this.lastCountPaper);if(this.timerBool){this.textPaperPerSec.setText(speed);this.lastCountPaper=this.countPaper}this.timerBool=!this.timerBool;this.arrayPPS.push(speed);
if(this.arrayPPS.length>5)this.arrayPPS.shift()},checkIfDangerous:function(){if(this.countPaper>80)return;if(this.isCanTear&&this.arrayPPS.length>2){var summ=this.arrayPPS[0]+this.arrayPPS[1]+this.arrayPPS[2];if(summ>30)if(Phaser.Utils.chanceRoll(35))this.tearPaper();else;}},tearPaper:function(){this.isCanTear=false;this.arrayPPS=[];this.updateTearMask(150);game.time.events.add(2E3,this.continueAfterTear,this).autoDestroy=true;this.isCanRoll=false;this.isPaperTear=true;this.isPotyanuto=false;this.tripTeatDistance=
0;this.movingSpeed=2;this.showInfo(3);this.checkFire()},continueAfterTear:function(){this.isPaperAdded=true;this.isCanRoll=true;this.isCanTear=true},initPaperRoll:function(vChageSkin){if(typeof vChageSkin==="undefined")vChageSkin=false;if(vChageSkin){var whatNet=[];var whatYest=[];for(i=0;i<15;i++)if(MainGame.papers[i]==0)whatNet.push(i);else whatYest.push(i);var num=whatYest[Math.floor(Math.random()*whatYest.length)]+1;if(Phaser.Utils.chanceRoll(10)&&whatNet.length>0){this.showInfo(4);num=whatNet[Math.floor(Math.random()*
whatNet.length)]+1}var skinPaper="paper"+num;this.paper_tile1.loadTexture(skinPaper);this.paper_tile2.loadTexture(skinPaper)}this.offsetPaperX=20;this.savedPositionY=0;this.isCanRoll=true;this.paper_tile1.tilePosition.y=0;this.paper_tile1.tilePosition.x=this.offsetPaperX;this.movingSpeed=0;this.deltaS=0;this.isCanTear=true;this.isPaperTear=false;this.tripDistance=0;this.paperDistance=0;this.countPaper=0;this.lastCountPaper=0;this.countPerfect=0;this.isFireEffect=false;this.arrayPPS=[];this.isPaperAdded=
true;this.isPotyanuto=false;this.paper_tile2.visible=true;this.circle1.visible=true;this.greyBlok.visible=true;this.updateEllipseSize();this.updateMask(200);this.numPaper++},updateEllipseSize:function(){var count=this.countMaxPaper-this.countPaper;var p=count/this.countMaxPaper;var maxEllipsW=57-25;var maxEllipsH=114-50;this.ellipsW=25+maxEllipsW*p;this.ellipsH=50+maxEllipsH*p;this.posBx=222;this.posBy=462;this.posAx=this.posBx;this.posAy=this.posBy-this.ellipsH;this.posCxf=this.posBx+57;this.posCx=
this.posBx+this.ellipsW;this.posCy=this.posBy;this.paper_tile2.height=this.ellipsH;this.paper_tile2.x=this.posBx;this.paper_tile2.y=this.posBy;this.greyBlok.clear();this.greyBlok.beginFill(3355443);this.greyBlok.drawRect(this.posBx,this.posBy,60,this.ellipsH);this.greyBlok.endFill();this.paper_tile1.x=this.posAx;this.paper_tile1.y=348;this.hole.x=222;this.hole.y=this.posBy;this.circle1.clear();this.circle1.beginFill(13421772);this.circle1.drawEllipse(this.posBx,this.posBy,this.ellipsW,this.ellipsH);
this.circle1.endFill();var delta=Math.floor(this.posCxf-this.posCx);this.paper_tile1.x=this.posAx-delta},initScroll:function(vObj1,vObj2){this.dragging=false;this.game.input.onDown.add(this.beginMove,this);this.game.input.onUp.add(this.endMove,this);this.objScroll=vObj1;this.objScroll_back=vObj2},beginMove:function(pointer,x,y){if(this.isClickedPause())return;if(MainGame.isPaused)return;if(this.gameOver)return;if(this.isShowTutorial){this.twInformerCompleted();this.isShowTutorial=false;SG_Hooks.tutorialFinished();
this.timerLevel.start()}this.checkIfDangerous();if(!this.isCanRoll)return;this.startY=this.game.input.y;this.isBeingDragged=true;this.deltaS=0;if(this.movingSpeed>0)this.movingSpeed*=.85},endMove:function(pointer,x,y){if(MainGame.isPaused)return;if(this.gameOver)return;if(!this.isCanRoll)return;this.isBeingDragged=false;if(this.deltaS>-10&&this.deltaS<0&&this.movingSpeed==0)this.movingSpeed=7},updateMask:function(vPosY){this.mask.clear();this.mask.beginFill(16777215);this.mask.drawEllipse(this.posBx+
this.paperW,this.posBy,this.ellipsW,this.ellipsH);this.mask.drawRect(this.posAx,this.posAy,this.paperW,this.ellipsH);this.mask.drawRect(this.posCx,this.posCy,this.paperW,vPosY);this.mask.endFill()},updateTearMask:function(vPosY){this.mask.clear();this.mask.beginFill(16711680);this.mask.drawEllipse(this.posBx+this.paperW,this.posBy,this.ellipsW,this.ellipsH);this.mask.drawRect(this.posAx,this.posAy,this.paperW,this.ellipsH);this.mask.drawRect(this.posCx,this.posCy,this.paperW,vPosY);var len=25;var startX=
this.posCx;var startY=this.posCy+vPosY;this.mask.moveTo(startX+25*0,startY);this.mask.lineTo(startX+25*0,startY+len);this.mask.lineTo(startX+25*1,startY);this.mask.lineTo(startX+25*0,startY);this.mask.moveTo(startX+25*1,startY);this.mask.lineTo(startX+25*2,startY+len);this.mask.lineTo(startX+25*3,startY);this.mask.lineTo(startX+25*1,startY);this.mask.moveTo(startX+25*3,startY);this.mask.lineTo(startX+25*4,startY+len);this.mask.lineTo(startX+25*5,startY);this.mask.lineTo(startX+25*3,startY);this.mask.moveTo(startX+
25*5,startY);this.mask.lineTo(startX+25*6,startY+len);this.mask.lineTo(startX+25*7,startY);this.mask.lineTo(startX+25*5,startY);this.mask.moveTo(startX+25*7,startY);this.mask.lineTo(startX+25*8,startY+len);this.mask.lineTo(startX+25*8,startY);this.mask.lineTo(startX+25*7,startY);this.mask.endFill()},update:function(){if(this.gameOver)return;if(!this.isPaperAdded)return;if(this.isBeingDragged){this.savedPositionY=this.objScroll.y;var y=this.game.input.y;var delta=this.startY-y;if(delta<0){this.startY=
y;this.tripDistance-=delta;this.tripTeatDistance-=delta;this.paperDistance-=delta;this.objScroll.y-=delta;this.deltaS=delta;this.movingSpeed=0}}else if(this.movingSpeed>1){var _distM=this.movingSpeed*.99;this.tripDistance+=_distM;this.tripTeatDistance+=_distM;this.paperDistance+=_distM;this.objScroll.y+=_distM;this.movingSpeed*=this.friction;this.savedPositionY=this.objScroll.y}else{var position=this.objScroll.y;var distance=Math.abs(position-this.savedPositionY);if(distance>4){this.movingSpeed=distance*
this.speedMult;if(this.movingSpeed>this.speedMax){this.movingSpeed=this.speedMax;if(this.countPerfect<4)this.countPerfect++;this.showInfo(0);if(this.countPerfect>0){this.showPerfectM(this.countPerfect);if(this.countPerfect==4){this.showInfo(6);this.addFireEffect()}}}else{this.countPerfect=0;this.mxPower.alpha=0;if(this.movingSpeed>this.speedGood)this.showInfo(1)}}}this.objScroll_back.y=this.objScroll.y;if(!this.isPotyanuto)if(this.isPaperTear)if(this.tripTeatDistance<450)this.updateTearMask(150+this.tripTeatDistance);
else{this.updateMask(550);this.isPaperTear=false;this.isPotyanuto=true}else if(this.tripDistance<350)this.updateMask(200+this.tripDistance);else{this.updateMask(550);this.isPotyanuto=true}if(this.tripDistance>this.countPaper*this.paperH){this.countPaper++;this.countPaperGame++;var _score=1;if(this.countPerfect>0)_score*=this.countPerfect+1;this.scoreGame+=_score;this.txtScore.setText(this.scoreGame)}if(this.paperDistance>this.paperH){this.updateEllipseSize();if(!this.isPaperTear)this.updateMask(500);
if(this.countPaper>=this.countMaxPaper)this.endPaperRoll()}},endPaperRoll:function(){this.isPaperAdded=false;this.objScroll.y=60;this.paper_tile2.visible=false;this.circle1.visible=false;this.greyBlok.visible=false;game.add.tween(this.paper_tile1).to({y:1E3},450,"Linear",true);game.time.events.add(600,this.removePaperRoll,this).autoDestroy=true;game.time.events.add(2E3,this.nextPaperRoll,this).autoDestroy=true;this.showInfo(5);this.checkFire();this.timerLevel.pause()},removePaperRoll:function(){MainGame.playSound(11);
game.add.tween(this.layerBack).to({alpha:0},200,"Linear",true,350);game.add.tween(this.layerBack).to({x:-650},550,"Back.easeIn",true)},nextPaperRoll:function(){MainGame.playSound(10);this.layerBack.x=650;this.layerBack.alpha=0;game.add.tween(this.layerBack).to({alpha:1},200,"Linear",true);game.add.tween(this.layerBack).to({x:0},550,"Back.easeOut",true);this.timerLevel.resume();this.initPaperRoll(true)},showTvAds:function(){SG_Hooks.triggerIncentivise(this.callBackx2coins)},callBackx2coins:function(result){if(result==
true){MainGame.state.countX2--;if(MainGame.state.countX2<=0)MainGame.state.btnCoinX2.buttonC.alpha=.6;MainGame.state.startCoinEffect(-MainGame.state.txtLevelCoins.width)}else{var layerText=MainGame.state.layerFinish.add(game.add.group());var plaha=layerText.add(game.add.image(320,290+140,"ss_main","panel_bestscore_0000"));plaha.anchor.setTo(.5);plaha.scale.setTo(1.05,1.5);plaha.tint=255;var noAdsToday=MainGame.addText(320,296+140,MainGame.GAME_TEXT.no_video,layerText,34,"#ffffff",.5,.5);MainGame.updateTextWidth(noAdsToday,
620);layerText.alpha=0;game.add.tween(layerText).to({alpha:1},300,Phaser.Easing.Linear.None,true).onComplete.add(function(){game.add.tween(layerText).to({alpha:0},300,Phaser.Easing.Linear.None,true,1E3)})}},callBackAds:function(result){if(result==true)console.log("ads")},tryAgain:function(){MainGame.goToState("Game")},goToMenu:function(){MainGame.fromGame=true;MainGame.goToState("Shop")}};